### ISSUE TITLE
Login server: Segmentation fault

### ISSUE THREAD

**Issue by ryder11** [rathena/rathena#1621]
rAthena was working perfectly fine for me until a couple of days ago.  I pulled in the latest changes from master and now when the character server connects to the login server, the login server dies immediately with the error "Segmentation fault".  There have been no modifications made to the source code.

I tried reverting back to the commit I had checked out before the error occurred but that didn't fix the issue.  I also tried it on a different VM with a fresh copy of Ubuntu and rAthena (the only changes were database related).

Output from Login server:
```
[Info]: Connection request of the char-server 'rAthena' @ <IPADDRESS>:6121 (account: 's1', pass: 'p1', ip: '<IPADDRESS>')
Segmentation fault (core dumped)
```
`gdb login-server core` returns:
```
Core was generated by `./login-server'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000040978f in safestrncpy.part.3.lto_priv.123 (dst=dst@entry=0x7ffc52219eb4 "", 
    src=0x0, n=10, n@entry=11) at strlib.c:376
376	strlib.c: No such file or directory.
```
`bt full` returns:
```
#0  0x000000000040978f in safestrncpy.part.3.lto_priv.123 (dst=dst@entry=0x7ffc52219eb4 "", 
    src=0x0, n=10, n@entry=11) at strlib.c:376
        d = 0x7ffc52219eb4 ""
        s = 0x0
#1  0x0000000000407cca in safestrncpy (n=11, src=<optimized out>, dst=0x7ffc52219eb4 "")
    at account.c:536
No locals.
#2  mmo_auth_fromsql (db=db@entry=0x7f05554f8f4c, acc=acc@entry=0x7ffc52219e00, 
    account_id=<optimized out>) at account.c:536
        sql_handle = 0x7f05554e599c
        data = 0x0
#3  0x0000000000407f93 in account_db_sql_load_num (self=0x7f05554f8f4c, acc=0x7ffc52219e00, 
    account_id=<optimized out>) at account.c:380
        db = 0x7f05554f8f4c
        account_id = <optimized out>
        acc = 0x7ffc52219e00
        self = 0x7f05554f8f4c
#4  account_db_sql_load_str.lto_priv.112 (self=0x7f05554f8f4c, acc=0x7ffc52219e00, 
    userid=0x7f05554bce75 "s1") at account.c:425
        db = 0x7f05554f8f4c
        sql_handle = 0x7f05554e599c
        esc_userid = "s1\000\061\000\177\000\000\373s\255U\005\177\000\000\001\200\255\373\005\177\000\000k>\266U\005\177\000\000\002\000\000\000\374\177\000\000\240\237!R\374\177\000\000\300"
        account_id = <optimized out>
        data = 0xd707c8 "E", <incomplete sequence \327>
#5  0x00000000004138d4 in login_mmo_auth (sd=0x7f05554bce5c, isServer=<optimized out>)
    at login.c:330
        acc = {account_id = 1, userid = "s1", '\000' <repeats 21 times>, 
          pass = "p1", '\000' <repeats 30 times>, sex = 83 'S', 
---Type <return> to continue, or q <return> to quit---
          email = "athena@athena.com", '\000' <repeats 22 times>, group_id = 0, 
          char_slots = 48 '0', state = 0, unban_time = 0, expiration_time = 0, logincount = 0, 
          lastlogin = "2016-10-13 00:14:18\000\000\000\000", last_ip = '\000' <repeats 15 times>, 
          birthdate = "\000\000\000\000\000\000\000\000\000\000", pincode = "\000\001\000\000", 
          pincode_change = 14084208}
        len = <optimized out>
        ip = "<IPADDRESS>\000\000\000\000\000"
#6  0x0000000000414e65 in logclif_parse_reqcharconnec.lto_priv.125 (fd=1377935028, fd@entry=7, 
    sd=0x0, sd@entry=0x7f05554bce5c, ip=0xa <error: Cannot access memory at address 0xa>, 
    ip@entry=0x7ffc5221a160 "<IPADDRESS>") at loginclif.c:429
        server_name = "rAthena", '\000' <repeats 12 times>
        message = "charserver - rAthena@<IPADDRESS>:6121\000\177\000\000П!R\374\177\000\000\000\000\000\000\000\000\000\000(\247\021W\005\177\000\000\270\071\022W\005\177\000\000\n\000\000\000\000\000\000\000\216", '\000' <repeats 19 times>, "\005\000\000\000\227\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000(\247\021W\005\177\000\000p\241!R\374\177\000\000\000e\022W\005\177\000\000\230\241!R\374\177\000\000\250a\022W\005\177\000\000\001\000\000\000\000\000\000\000=\327\360V\005\177\000\000\000\000\000\000\000\000\000\000(\247\021W\005\177\000\000\005\000\000\000\001", '\000' <repeats 11 times>...
        result = 0
#7  0x000000000040c9f8 in logclif_parse (fd=<optimized out>) at loginclif.c:532
        command = <optimized out>
        next = 1
        sd = 0x7f05554bce5c
        ip = "<IPADDRESS>\000\000\000\000\000"
        ipl = <optimized out>
        __FUNCTION__ = "logclif_parse"
#8  0x0000000000403e45 in do_sockets (next=<optimized out>) at socket.c:853
        rfd = {__fds_bits = {128, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 999998}
---Type <return> to continue, or q <return> to quit---
        ret = 0
        i = 7
#9  main (argc=<optimized out>, argv=<optimized out>) at core.c:368
No locals.
```

Let me know if there is anything else I can provide.  If anyone has a potential fix, please let me know...

**Comment by cydh** [comment]
git hash please

**Comment by Lemongrass3110** [comment]
Side note:
If you do blank out your ip address you should be aware that you should not post your server user passwords here and of course you should not use the default settings...

Which MySQL version do you use? This looks like birthdate was NULL instead of '0000-00-00'.
Any changes to your login table?

**Comment by ryder11** [comment]
@Lemongrass3110, that's exactly what it is!  I'm using MySQL 5.7.11 in strict mode and doesn't accept default values of '0000-00-00'.  I updated all of the DATETIME fields to default to the CURRENT_TIMESTAMP and must have set the birthdate to be NULL.  Thank you so much!

**Comment by Lemongrass3110** [comment]
Duplicate of #1210
