### ISSUE TITLE
Crash Server with last rev

### ISSUE THREAD

**Issue by ryonzito** [rathena/rathena#171]
My server is active with gdb to know the reason for the crash and the server crashed and gave this error:
````
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff89de7000
Core was generated by `./map-server_sql'.
Program terminated with signal 11, Segmentation fault.
#0 0x00000000004caa0f in pop_stack (st=0x2ba0db4a626c, start=0, end=0)
at script.c:2956
2956 struct script_stack* stack = st->stack;
(gdb) bt full
#0 0x00000000004caa0f in pop_stack (st=0x2ba0db4a626c, start=0, end=0)
at script.c:2956
stack = 0x0
data = 
i = 
FUNCTION = "pop_stack"
#1 0x00000000004ce4a1 in run_func (st=0x2ba0db4a626c) at script.c:3502
data = 
i = 
start_sp = 
end_sp = 
func = 279
#2 0x00000000004e0710 in run_script_main (st=0x2ba0db4a626c) at script.c:3724
c = C_FUNC
cmdcount = 655342
gotocount = 2048
sd = 
stack = 0x2ba0e717c34c
#3 0x00000000004e0ba9 in run_script_timer (tid=,
tick=, id=193058, data=47969873846892)
at script.c:3607
st = 0x2ba0db4a626c
node = 0x2ba0e883136c
---Type to continue, or q to quit---
sd = 
#4 0x00000000005b461f in do_timer (tick=10535892) at timer.c:370
tid = 19668
diff = 0
FUNCTION = "do_timer"
#5 0x00000000005b05ac in main (argc=1, argv=0x7fff89c872e8) at core.c:370
next = 
(gdb)
````

**Comment by aleos89** [comment]
The only report of this kind and not enough info.
