### ISSUE TITLE
Crash map server

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#200]
My server is online and gave this crash what would that be?

[Error]: pc_bonus2: SP_ADD_ITEM_HEAL_RATE Invalid item with id 37
[Error]: pc_bonus2: SP_ADD_ITEM_HEAL_RATE Invalid item with id 37
[Error]: Server received crash signal! Attempting to save all online characters!
http://pastebin.com/KxsJmNJf

**Comment by cydh** [comment]
````
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff96da4000
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004b12c4 in clif_send (
    buf=0x7fff96c98e20 "\362\001\374\305\036", len=20, bl=0x16e221f0,
    type=GUILD) at clif.c:819
819                                             if( packet_db[sd->packet_ver][RBUFW(buf,0)].len )
(gdb) bt full
#0  0x00000000004b12c4 in clif_send (
    buf=0x7fff96c98e20 "\362\001\374\305\036", len=20, bl=0x16e221f0,
    type=GUILD) at clif.c:819
        i = 1
        sd = <value optimized out>
        p = <value optimized out>
        g = 0x2ad7149bc714
        bg = <value optimized out>
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = -33686019
        iter = <value optimized out>
        __FUNCTION__ = "clif_send"
#1  0x00000000004b6100 in clif_guild_memberlogin_notice (g=0x2ad7149bc714,
    idx=26, flag=0) at clif.c:8061
        buf = "\362\001\374\305\036\000\333\361\002", '\000' <repeats 15 times>, "lI\246\003\327*\000\000\374\305\036\000\377\377\377\377#o`\000\000\000\000\000\374\305\036\000\377\377\377\377Pn`\000\000\000\000"
        sd = 0x12afd60
        __FUNCTION__ = "clif_guild_memberlogin_notice"
#2  0x00000000004d0e30 in guild_recv_memberinfoshort (
---Type <return> to continue, or q <return> to quit---
    guild_id=<value optimized out>, account_id=2016764, char_id=192987,
    online=0, lv=150, class_=4065) at guild.c:1127
        i = <value optimized out>
        alv = <value optimized out>
        c = <value optimized out>
        idx = 26
        om = <value optimized out>
        oldonline = 1
        g = 0x2ad7149bc714
#3  0x00000000004dee56 in intif_parse_GuildMemberInfoShort (
    fd=<value optimized out>) at intif.c:1538
No locals.
#4  0x00000000004dff3c in intif_parse (fd=7) at intif.c:3128
        packet_len = 19
        cmd = <value optimized out>
#5  0x000000000048fd00 in chrif_parse (fd=7) at chrif.c:1767
        r = <value optimized out>
        cmd = 14389
        packet_len = 10
#6  0x0000000000603265 in do_sockets (next=<value optimized out>)
    at socket.c:849
        rfd = {__fds_bits = {128, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 10000}
---Type <return> to continue, or q <return> to quit---
        ret = 0
        i = 7
#7  0x0000000000601d03 in main (argc=1, argv=0x7fff96c99558) at core.c:364
        next = 2
````
the real reason is this one.
what's ur rev/hash?
I ever see this issue one bug tracker, still not fixed yet. xD
