### ISSUE TITLE
Some crash here i think with MOB or Clone

### ISSUE THREAD

**Issue by van84** [rathena/rathena#230]
```
0x00000000005ebf2c in map_delblock.part.4.3997 (bl=0x7fffa5c9363c) at map.c:360
360                             map[bl->m].block[pos] = bl->next;
#0  0x00000000005ebf2c in map_delblock.part.4.3997 (bl=0x7fffa5c9363c) at map.c:360
#1  0x00000000005f14d0 in map_delblock (bl=0x7fffa5c9363c) at map.c:334
#2  0x0000000000448adf in unit_remove_map_ (bl=0x7fffa5c9363c, clrtype=CLR_RESPAWN, file=0x610762 "unit.c", line=2559, func=0x607190 <__FUNCTION__.18469.80639> "unit_remove_map_pc") at unit.c:2540
#3  0x0000000000448b6d in unit_remove_map_pc (sd=0x19993190, clrtype=CLR_RESPAWN) at unit.c:2559
#4  0x00000000005f6a5a in map_quit (sd=0x19993190) at map.c:1751
#5  0x00000000005e2e9e in clif_quitsave (fd=183, sd=0x19993190) at clif.c:1692
#6  0x00000000005b7485 in clif_parse.10327 (fd=183) at clif.c:17346
#7  0x000000000041ed9d in send_shortlist_do_sends () at socket.c:1596
#8  0x000000000041d83b in do_sockets (next=50) at socket.c:908
#9  0x000000000041bca2 in main (argc=1, argv=0x7fffffffe348) at core.c:376
#0  0x00000000005ebf2c in map_delblock.part.4.3997 (bl=0x7fffa5c9363c) at map.c:360
        pos = 9
#1  0x00000000005f14d0 in map_delblock (bl=0x7fffa5c9363c) at map.c:334
No locals.
#2  0x0000000000448adf in unit_remove_map_ (bl=0x7fffa5c9363c, clrtype=CLR_RESPAWN, file=0x610762 "unit.c", line=2559, func=0x607190 <__FUNCTION__.18469.80639> "unit_remove_map_pc") at unit.c:2540
        ud = 0x7fffa5c9365c
        sc = 0x0
#3  0x0000000000448b6d in unit_remove_map_pc (sd=0x19993190, clrtype=CLR_RESPAWN) at unit.c:2559
No locals.
#4  0x00000000005f6a5a in map_quit (sd=0x19993190) at map.c:1751
        i = 21
#5  0x00000000005e2e9e in clif_quitsave (fd=183, sd=0x19993190) at clif.c:1692
No locals.
#6  0x00000000005b7485 in clif_parse.10327 (fd=183) at clif.c:17346
        cmd = 32767
        packet_ver = 0
        packet_len = 4310435
        err = -929840348
        sd = 0x19993190
        pnum = 0
#7  0x000000000041ed9d in send_shortlist_do_sends () at socket.c:1596
        fd = 183
        idx = 5
        bit = 23
        i = 0
#8  0x000000000041d83b in do_sockets (next=50) at socket.c:908
        rfd = {__fds_bits = {0, 0, 36028797018963968, 0 <repeats 13 times>}}
        timeout = {tv_sec = 0, tv_usec = 43943}
        ret = 0
        i = 184
```

**Comment by anacondaqq** [comment]
is this issue still actual? A lot of code is changed...

**Comment by Lemongrass3110** [comment]
Since we do not have the git hash it will be hard to find what is going wrong here.
I will add "need more info tag" so that someone can look into this if he wants to or if the issuer might provide the hash.
