### ISSUE TITLE
map server crash when GM executes any command

### ISSUE THREAD

**Issue by OmegaRedBR** [rathena/rathena#2421]
* **rAthena Hash:**  8222208

* **Client Date:** 20150916

* **Server Mode:** Pre-Renewal

* **Description of Issue**: 
  * Result: Map server crash, freeze and not display errors
  * How to Reproduce: Login with a GM and run any command, eg ``` `@date or @commands` ```
 

* **Modifications that may affect results**: 
 Without modifications or scripts, only clean rAthena installation.

* **Operating System:**
 Linux

* **gdb logs**:

```
`@date`
(gdb) bt full
#0  0x00007ffff796d49d in read () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff7092aa0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#2  0x00007ffff7092b21 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#3  0x00007ffff7076cba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#4  0x00007ffff7077b2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#5  0x00007ffff706a75c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#6  0x00007ffff706bc56 in cli_read_query_result () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#7  0x00007ffff706649d in execute () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#8  0x00007ffff7066f62 in cli_stmt_execute () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#9  0x00007ffff70687ea in mysql_stmt_execute () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#10 0x00000000004aa7fa in SqlStmt_Execute ()
No symbol table info available.
#11 0x00000000004bfb70 in log_atcommand.part.4 ()
No symbol table info available.
#12 0x000000000052f01c in is_atcommand ()
No symbol table info available.
#13 0x00000000004d72fd in clif_process_message.lto_priv.564 ()
No symbol table info available.
#14 0x00000000004d82a2 in clif_parse_GlobalMessage ()
No symbol table info available.
#15 0x00000000004bb918 in clif_parse.lto_priv.546 ()
No symbol table info available.
#16 0x0000000000414275 in main ()
No symbol table info available.
(gdb)

```
```
@commands
(gdb) bt full
#0  0x00007ffff796d49d in read () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff7092aa0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#2  0x00007ffff7092b21 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#3  0x00007ffff7076cba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#4  0x00007ffff7077b2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#5  0x00007ffff706a75c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#6  0x00007ffff706bc56 in cli_read_query_result () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#7  0x00007ffff706649d in execute () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#8  0x00007ffff7066f62 in cli_stmt_execute () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#9  0x00007ffff70687ea in mysql_stmt_execute () from /usr/lib64/mysql/libmysqlclient.so.18
No symbol table info available.
#10 0x00000000004aa7fa in SqlStmt_Execute ()
No symbol table info available.
#11 0x00000000004bfb70 in log_atcommand.part.4 ()
No symbol table info available.
#12 0x000000000052f01c in is_atcommand ()
No symbol table info available.
#13 0x00000000004d72fd in clif_process_message.lto_priv.564 ()
No symbol table info available.
#14 0x00000000004d82a2 in clif_parse_GlobalMessage ()
No symbol table info available.
#15 0x00000000004bb918 in clif_parse.lto_priv.546 ()
No symbol table info available.
#16 0x0000000000414275 in main ()
No symbol table info available.
(gdb)
```

**Comment by admkakaroto** [comment]
client 2017-05-31, I can not reproduce this.

**Comment by Daegaladh** [comment]
Me neither, I think you can close the issue.
