### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by van84** [rathena/rathena#256]
```
0x00000000005f177c in map_moveblock (bl=0x7fffa797c664, x1=40, y1=147, tick=250280784) at map.c:442
442                                     skill_unit_move_unit_group(skill_id2group(sc->data[SC_DANCING]->val2), bl->m, x1-x0, y1-y0);
#0  0x00000000005f177c in map_moveblock (bl=0x7fffa797c664, x1=40, y1=147, tick=250280784) at map.c:442
#1  0x0000000000443255 in unit_walktoxy_timer.79940 (tid=31095, tick=250280784, id=110057057, data=252) at unit.c:297
#2  0x0000000000420204 in do_timer (tick=250280787) at timer.c:371
#3  0x000000000041bc95 in main (argc=1, argv=0x7fffffffe348) at core.c:375
#0  0x00000000005f177c in map_moveblock (bl=0x7fffa797c664, x1=40, y1=147, tick=250280784) at map.c:442
        x0 = 41
        y0 = 146
        sc = 0x7fffa797c964
        moveblock = 0
#1  0x0000000000443255 in unit_walktoxy_timer.79940 (tid=31095, tick=250280784, id=110057057, data=252) at unit.c:297
        i = 420
        x = 40
        y = 147
        dx = -1
        dy = 1
        dir = 1 '\001'
        bl = 0x7fffa797c664
        ud = 0x7fffa797c684
        sd = 0x0
        md = 0x7fffa797c664
        mrd = 0x0
        ed = 0x0
        pd = 0x0
        hd = 0x0
#2  0x0000000000420204 in do_timer (tick=250280787) at timer.c:371
        tid = 31095
        diff = -3
#3  0x000000000041bc95 in main (argc=1, argv=0x7fffffffe348) at core.c:375
        next = 50
  Id   Target Id         Frame
* 1    Thread 0x7ffff7fec740 (LWP 17438) "map-server" 0x00000000005f177c in map_moveblock (bl=0x7fffa797c664, x1=40, y1=147, tick=250280784) at map.c:442

Thread 1 (Thread 0x7ffff7fec740 (LWP 17438)):
#0  0x00000000005f177c in map_moveblock (bl=0x7fffa797c664, x1=40, y1=147, tick=250280784) at map.c:442
        x0 = 41
        y0 = 146
        sc = 0x7fffa797c964
        moveblock = 0
#1  0x0000000000443255 in unit_walktoxy_timer.79940 (tid=31095, tick=250280784, id=110057057, data=252) at unit.c:297
        i = 420
        x = 40
        y = 147
        dx = -1
        dy = 1
        dir = 1 '\001'
        bl = 0x7fffa797c664
        ud = 0x7fffa797c684
        sd = 0x0
        md = 0x7fffa797c664
        mrd = 0x0
        ed = 0x0
        pd = 0x0
        hd = 0x0
#2  0x0000000000420204 in do_timer (tick=250280787) at timer.c:371
        tid = 31095
        diff = -3
#3  0x000000000041bc95 in main (argc=1, argv=0x7fffffffe348) at core.c:375
        next = 50
A debugging session is active.

        Inferior 1 [process 17438] will be killed.
```

**Comment by raynra** [comment]
In keeping a consistency with other bug reports, please provide the following information:

Git Hash/Date:
Client Date:
Source Code Modifications?:
Description of Issue:
How to Reproduce:

This will also help us troubleshoot the issue in a more effective and timely manner.

**Comment by van84** [comment]
i am using svn Last Changed Rev: 17698

source code modification: unknown

cannot reproduce as will but crash every day

**Comment by anacondaqq** [comment]
is this issue stil actual after so long time?
