### ISSUE TITLE
map server crash

### ISSUE THREAD

**Issue by hurtsky** [rathena/rathena#2894]
* **rAthena Hash**: 9d4fa62e6527ff850957049bf2625a6a7a2bf62c

* **Client Date**:  20170614

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result:  after player login, the map server just crash
  * Expected Result:  no crash
  * How to Reproduce: 
after player login, the map server just crash
havent crash on this hash : 31988abd1919a42e7ccedaf597fa13d4a7308865
just update till 9d4fa62e6527ff850957049bf2625a6a7a2bf62c 
and getting the mapserver crash
bt full
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004dae87 in npc_event_sub(map_session_data*, event_data*, char const*) ()
(gdb) bt full
#0  0x00000000004dae87 in npc_event_sub(map_session_data*, event_data*, char const*) ()
No symbol table info available.
#1  0x00000000004eabe2 in npc_script_event(map_session_data*, npce_event) ()
No symbol table info available.
#2  0x000000000048fc0f in clif_parse_LoadEndAck (sd=0x5b72c20, 
    fd=<optimized out>) at clif.cpp:10414
        lv = <optimized out>
        guild_notice = true
#3  0x000000000046b938 in clif_parse (fd=<optimized out>) at clif.cpp:20221
        cmd = <optimized out>
        packet_len = 2
        sd = 0x5b72c20
        pnum = 0
        cmd2 = 768034209
#4  0x000000000040b6d5 in main ()
No symbol table info available.
```

* **Modifications that may affect results**: not make any source changes
  
  none

**Comment by hurtsky** [comment]
okay i fixed this, this because i had alot of duplicate scripts that use onpclogin/logout that clear same variable on table at the same time.
