### ISSUE TITLE
Killing multiple monster with dispbottom attached

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#2971]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/09cbf2dfa61e3eed34936e7cd2e312c02d20a211

* **Client Date**: 2015-11-04 Ragexe

* **Server Mode**: Pre Renewal

* **Description of Issue**: Everytime I killed multiple monsters, with dispbottom on it the map crashed.
 * **Crash Dumped**:
```
#0  status_change_end_ (bl=0x7fffe6398cf4, type=13, tid=-1,
    file=0x5d1f70 "status.c", line=11783) at status.c:11832
        sc = <optimized out>
        sce = 0x2e41da100000000
        status = 0x7fffe6399110
        vd = <optimized out>
        opt_flag = <optimized out>
        sd = <optimized out>
        calc_flag = <optimized out>
        line = 11783
        file = 0x5d1f70 "status.c"
        tid = -1
        type = 13
        bl = 0x7fffe6398cf4
        __func__ = "status_change_end_"
        __FUNCTION__ = "status_change_end_"
#1  0x00000000004839f8 in status_change_clear (bl=0x7fffe6398cf4, type=0)
    at status.c:11783
        i = 13
#2  0x00000000005990bd in status_damage (src=<optimized out>,
    target=0x7fffe6398cf4, dhp=<optimized out>, dsp=<optimized out>,
    walkdelay=916, flag=5) at status.c:1790
        status = <optimized out>
```
The part of my script: 
```
	for(.@i = 0; .@i < 5; .@i++) {
		if(killedrid == SECRET_REIN_MOBID[.@i] && SECRET_REIN_MOBHUNT[.@i]) {
			SECRET_REIN_MOBHUNT[.@i]--;
			dispbottom "[ Valkyrie : you killed " + (SECRET_REIN_MOBHUNT_MAX[.@i] - SECRET_REIN_MOBHUNT[.@i]) + " out of " + SECRET_REIN_MOBHUNT_MAX[.@i] + " " + getmonsterinfo(SECRET_REIN_MOBID[.@i],MOB_NAME)+"' monsters ]";
			end;
		}
	}
```

**Comment by Lemongrass3110** [comment]
Upgrade your emulator and try to reproduce the issue.
Your emulator is more than one year behind the current version...
