### ISSUE TITLE
Unordered Map Crash

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#3432]
* **rAthena Hash**: ae89b3a

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: MAP SERVER CRASH
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

GDB LOG

```
[root@ragnarok-sg rathena]# gdb map-server core.29086
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/rathena/map-server...done.
[New LWP 29086]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (this=this@entry=0xf4bc08 <map+6478152>,
    __n=15, __k=@0x7ffe0c85a3ee: 61, __code=18446744073709528046)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable.h:1430
1430          for (__node_type* __p = static_cast<__node_type*>(__prev_p->_M_nxt);;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt full
#0  std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (this=this@entry=0xf4bc08 <map+6478152>,
    __n=15, __k=@0x7ffe0c85a3ee: 61, __code=18446744073709528046)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable.h:1430
        __p = <optimized out>
        __prev_p = 0x41
#1  0x00000000004cd3bc in _M_find_node (__c=18446744073709528046, __key=@0x7ffe0c85a3be: 0,
    __key@entry=@0x7ffe0c85a3be: -23570, __bkt=<optimized out>,
    this=this@entry=0xf4bc08 <map+6478152>)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable.h:632
        __before_n = <optimized out>
#2  std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find (this=this@entry=0xf4bc08 <map+6478152>,
    __k=__k@entry=@0x7ffe0c85a3ee: 61)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable.h:1307
        __code = 61
        __n = <optimized out>
        __p = <optimized out>
#3  0x00000000004caf55 in find (__x=@0x7ffe0c85a3ee: 61, this=0xf4bc08 <map+6478152>)
    at /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/unordered_map.h:615
No locals.
Python Exception <class 'gdb.error'> There is no member or method named _M_bbegin.:
#4  umap_get<short, int> (defaultValue=0, key=61, map=std::unordered_map with 13 elements)
    at ../common/utilities.hpp:85
No locals.
#5  map_getmapflag_sub (m=1205, mapflag=mapflag@entry=MF_NOCOSTUME, args=args@entry=0x0)
    at map.cpp:4516
        mapdata = 0xf4bbc0 <map+6478080>
        __FUNCTION__ = "map_getmapflag_sub"
#6  0x000000000050c48a in pc_set_costume_view (sd=sd@entry=0x573f240) at pc.cpp:12546
        i = <optimized out>
---Type <return> to continue, or q <return> to quit---
        head_top = 804
        robe = 1
        head_low = 56
        head_mid = 100
        id = <optimized out>
        sd = 0x573f240
#7  0x000000000049e933 in clif_parse_LoadEndAck (fd=<optimized out>, sd=0x573f240)
    at clif.cpp:10296
        guild_notice = false
        mapdata = <optimized out>
#8  0x000000000046bd08 in clif_parse (fd=<optimized out>) at clif.cpp:20627
        cmd = <optimized out>
        packet_len = 2
        sd = 0x573f240
        pnum = 0
        cmd2 = 889050316
#9  0x000000000040b0c5 in do_sockets (next=<optimized out>) at socket.cpp:917
        rfd = {fds_bits = {8192, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 10963}
        ret = 0
        i = 13
#10 main (argc=<optimized out>, argv=<optimized out>) at core.cpp:368
No locals.
(gdb)
```

MAP SERVER MSG LOG
```

(08/20/2018 07:28:20) [ Warning ] : itemdb_parse_dbrow: Duplicate item name for "Indo_CDA02"
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 1 has 0 items, 9 are required. Filling with Apples...
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 2 has 0 items, 8 are required. Filling with Apples...
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 3 has 0 items, 7 are required. Filling with Apples...
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 4 has 0 items, 6 are required. Filling with Apples...
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 5 has 0 items, 5 are required. Filling with Apples...
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 6 has 0 items, 4 are required. Filling with Apples...
(08/20/2018 07:28:21) [ Warning ] : itemdb_parse_roulette_db: Level 7 has 0 items, 3 are required. Filling with Apples...
(08/20/2018 11:28:43) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/20/2018 12:34:42) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/20/2018 15:01:05) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/20/2018 16:19:13) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/20/2018 17:11:37) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Chaos (id=110018515).
(08/20/2018 17:24:27) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/20/2018 20:35:06) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/20/2018 21:15:13) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/20/2018 23:18:45) [ Warning ] : Incorrect use of 'close' command! (source:PVP Gate / path:npc/mazvi/mazvi_npc1.txt)
(08/21/2018 01:42:54) [ Warning ] : Incorrect use of 'close' command! (source:PVP Gate / path:npc/mazvi/mazvi_npc1.txt)
(08/21/2018 07:59:32) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not PemanduCommand (id=110019288).
(08/21/2018 12:27:40) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/21/2018 12:45:59) [ Error ] : npc_click: npc_id != 0
(08/21/2018 14:23:41) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Healer#prt (id=110019270).
(08/21/2018 14:26:53) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/21/2018 14:26:56) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/21/2018 18:51:25) [ Debug ] : NPCEvent 'Marjana#poison::OnDisable' not found! (source:  #room1timer)
(08/21/2018 19:54:41) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 19:54:44) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 19:55:44) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 19:55:50) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 20:02:00) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 20:02:01) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 20:02:06) [ Warning ] : clif_process_message: Player 'Gembelion' sent an unterminated name!
(08/21/2018 21:47:41) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/21/2018 23:40:35) [ Error ] : map_addblock: out-of-bounds coordinates ("moc_prydn2",167,-5), map is 204x204
(08/22/2018 00:10:30) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/22/2018 00:34:32) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/22/2018 00:42:26) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/22/2018 00:51:39) [ Error ] : map_addblock: out-of-bounds coordinates ("man_fild03",287,-7), map is 400x400
(08/22/2018 14:44:25) [ Error ] : map_addblock: out-of-bounds coordinates ("man_fild02",400,316), map is 400x400
(08/22/2018 15:05:33) [ Error ] : map_addblock: out-of-bounds coordinates ("mjolnir_04",-2,279), map is 400x400
(08/22/2018 16:06:59) [ Error ] : intif_parse_Mail_delete: char not found 150027
(08/22/2018 17:28:15) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/22/2018 17:56:22) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/22/2018 18:00:37) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/22/2018 21:02:12) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/22/2018 23:25:25) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/22/2018 23:46:15) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Apprentice Craftsman (id=110001575).
(08/22/2018 23:51:51) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/23/2018 01:34:28) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Guardian of Power#pa082 (id=110014182).
(08/23/2018 13:38:30) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/23/2018 16:16:49) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/23/2018 16:28:28) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/23/2018 21:41:39) [ Error ] : npc_click: npc_id != 0
(08/23/2018 23:20:30) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/23/2018 23:52:35) [ Error ] : quest_add: Character 151998 already has quest 5182.
(08/23/2018 23:52:35) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/23/2018 23:52:35) [ Debug ] : Function: setquest (1 parameter):
(08/23/2018 23:52:35) [ Debug ] : Data: number value=5182
(08/23/2018 23:57:24) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/23/2018 23:57:24) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/23/2018 23:57:24) [ Debug ] : Function: setquest (1 parameter):
(08/23/2018 23:57:24) [ Debug ] : Data: number value=5174
(08/24/2018 00:05:01) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/24/2018 00:05:01) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/24/2018 00:05:01) [ Debug ] : Function: setquest (1 parameter):
(08/24/2018 00:05:01) [ Debug ] : Data: number value=5174
(08/24/2018 00:11:42) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/24/2018 00:11:42) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/24/2018 00:11:42) [ Debug ] : Function: setquest (1 parameter):
(08/24/2018 00:11:42) [ Debug ] : Data: number value=5174
(08/24/2018 00:17:14) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Reset Doctor (id=110019242).
(08/24/2018 00:17:22) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/24/2018 00:17:22) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/24/2018 00:17:22) [ Debug ] : Function: setquest (1 parameter):
(08/24/2018 00:17:22) [ Debug ] : Data: number value=5174
(08/24/2018 00:22:24) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/24/2018 09:30:08) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/24/2018 10:34:11) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Secretary Lime Evenor (id=110014603).
(08/24/2018 11:04:55) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/24/2018 12:46:49) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/24/2018 13:52:07) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not King#dk11 (id=111096182).
(08/24/2018 14:08:23) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Seiyablem#prt (id=110001821).
(08/24/2018 14:11:48) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Leablem#prt (id=110001831).
(08/24/2018 14:15:41) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/24/2018 14:33:42) [ Debug ] : Source (NPC): Hugin at glast_01 (204,273)
(08/24/2018 14:33:43) [ Debug ] : Source (NPC): Hugin at glast_01 (204,273)
(08/24/2018 14:33:44) [ Debug ] : Source (NPC): Hugin at glast_01 (204,273)
(08/24/2018 18:25:06) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/24/2018 19:57:13) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Secretary Lime Evenor (id=110014603).
(08/24/2018 19:58:58) [ Error ] : buildin_unitwarp: Unit with ID '0' is not found.
(08/24/2018 20:01:33) [ Error ] : quest_change: Character 153997 already has quest 9316.
(08/24/2018 20:01:33) [ Debug ] : Source (NPC): Emmitt White at dali (98,141)
(08/24/2018 20:01:33) [ Debug ] : Function: changequest (2 parameters):
(08/24/2018 20:01:33) [ Debug ] : Data: number value=9315
(08/24/2018 20:01:33) [ Debug ] : Data: number value=9316
(08/24/2018 20:22:04) [ Error ] : buildin_unitwarp: Unit with ID '0' is not found.
(08/24/2018 20:24:45) [ Error ] : quest_change: Character 153711 already has quest 9316.
(08/24/2018 20:24:45) [ Debug ] : Source (NPC): Emmitt White at dali (98,141)
(08/24/2018 20:24:45) [ Debug ] : Function: changequest (2 parameters):
(08/24/2018 20:24:45) [ Debug ] : Data: number value=9315
(08/24/2018 20:24:45) [ Debug ] : Data: number value=9316
(08/24/2018 20:48:48) [ Error ] : buildin_unitwarp: Unit with ID '0' is not found.
(08/24/2018 20:49:47) [ Error ] : quest_change: Character 153759 already has quest 9316.
(08/24/2018 20:49:47) [ Debug ] : Source (NPC): Emmitt White at dali (98,141)
(08/24/2018 20:49:47) [ Debug ] : Function: changequest (2 parameters):
(08/24/2018 20:49:47) [ Debug ] : Data: number value=9315
(08/24/2018 20:49:47) [ Debug ] : Data: number value=9316
(08/24/2018 20:53:23) [ Error ] : buildin_unitwarp: Unit with ID '0' is not found.
(08/24/2018 22:01:59) [ Error ] : intif_parse_Mail_delete: char not found 150027
(08/24/2018 22:25:19) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/24/2018 23:08:24) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/24/2018 23:08:53) [ Error ] : map_addblock: out-of-bounds coordinates ("moc_fild22",328,-4), map is 400x400
(08/24/2018 23:29:15) [ Error ] : map_addblock: out-of-bounds coordinates ("prt_maze03",58,200), map is 200x200
(08/24/2018 23:52:24) [ Warning ] : clif_parse_Mail_read: char 'Litz' trying to read a message not the inbox.
(08/25/2018 08:21:39) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/25/2018 09:04:56) [ Debug ] : Source (NPC): Dimensional Gorge Piece at gef_fild10 (242,202)
(08/25/2018 10:44:41) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/25/2018 10:53:13) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/25/2018 10:53:15) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/25/2018 11:03:12) [ Debug ] : Source (NPC): Tower Protection Stone at e_tower (81,105)
(08/25/2018 11:15:30) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/25/2018 12:14:55) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper#pay (id=110019221).
(08/25/2018 12:23:24) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper#pay (id=110019221).
(08/25/2018 12:32:31) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper#pay (id=110019221).
(08/25/2018 14:00:24) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/25/2018 19:11:59) [ Error ] : intif_parse_Mail_delete: char not found 150039
(08/25/2018 21:37:12) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/25/2018 22:34:37) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Job Master (id=110018505).
(08/25/2018 22:40:51) [ Error ] : map_addblock: out-of-bounds coordinates ("moc_fild22",223,-1), map is 400x400
(08/26/2018 00:59:40) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Healer#prt (id=110019270).
(08/26/2018 02:24:51) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/26/2018 09:09:36) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper#gef (id=110019203).
(08/26/2018 17:53:44) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/26/2018 19:21:21) [ Error ] : delete_timer error : function mismatch 0x5bba00(skill_castend_pos) != 0x5bcb60(skill_castend_id)
(08/26/2018 19:21:21) [ Error ] : delete timer error : skill_id : -2
(08/26/2018 19:21:23) [ Error ] : skill_castend_pos: Timer mismatch -1!=773
(08/26/2018 19:30:12) [ Error ] : delete_timer error : function mismatch 0x5bba00(skill_castend_pos) != 0x5bcb60(skill_castend_id)
(08/26/2018 19:30:12) [ Error ] : delete timer error : skill_id : -2
(08/26/2018 19:30:14) [ Error ] : skill_castend_pos: Timer mismatch -1!=2609
(08/26/2018 19:30:24) [ Error ] : delete_timer error : function mismatch 0x5bba00(skill_castend_pos) != 0x5bcb60(skill_castend_id)
(08/26/2018 19:30:24) [ Error ] : delete timer error : skill_id : -2
(08/26/2018 19:30:24) [ Error ] : skill_castend_pos: Timer mismatch -1!=1841
(08/26/2018 19:56:49) [ Error ] : delete_timer error : function mismatch 0x5bba00(skill_castend_pos) != 0x5bcb60(skill_castend_id)
(08/26/2018 19:56:49) [ Error ] : delete timer error : skill_id : -2
(08/26/2018 19:56:50) [ Error ] : skill_castend_pos: Timer mismatch -1!=2943
(08/26/2018 22:02:35) [ Error ] : chat_createnpcchat: npc 'Ozzaz' already has a chatroom, cannot create new one!
(08/26/2018 22:02:37) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Ozzaz (id=110019240).
(08/26/2018 22:02:37) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Ozzaz (id=110019240).
(08/26/2018 22:02:37) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Ozzaz (id=110019240).
(08/26/2018 22:02:42) [ Error ] : chat_createnpcchat: npc 'Ozzaz' already has a chatroom, cannot create new one!
(08/26/2018 22:02:52) [ Error ] : chat_createnpcchat: npc 'Ozzaz' already has a chatroom, cannot create new one!
(08/26/2018 22:02:52) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Ozzaz (id=110019240).
(08/26/2018 22:42:39) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 22:42:39) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 22:42:39) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 22:42:39) [ Debug ] : Data: number value=5174
(08/26/2018 22:48:36) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 22:48:36) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 22:48:36) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 22:48:36) [ Debug ] : Data: number value=5174
(08/26/2018 22:55:57) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 22:55:57) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 22:55:57) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 22:55:57) [ Debug ] : Data: number value=5174
(08/26/2018 23:03:44) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 23:03:44) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 23:03:44) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 23:03:44) [ Debug ] : Data: number value=5174
(08/26/2018 23:09:10) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 23:09:10) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 23:09:10) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 23:09:10) [ Debug ] : Data: number value=5174
(08/26/2018 23:15:15) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 23:15:15) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 23:15:15) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 23:15:15) [ Debug ] : Data: number value=5174
(08/26/2018 23:21:35) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 23:21:35) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 23:21:35) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 23:21:35) [ Debug ] : Data: number value=5174
(08/26/2018 23:27:25) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 23:27:25) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 23:27:25) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 23:27:25) [ Debug ] : Data: number value=5174
(08/26/2018 23:33:22) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/26/2018 23:33:22) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/26/2018 23:33:22) [ Debug ] : Function: setquest (1 parameter):
(08/26/2018 23:33:22) [ Debug ] : Data: number value=5174
(08/27/2018 00:14:55) [ Error ] : quest_add: Character 151998 already has quest 5179.
(08/27/2018 00:14:55) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/27/2018 00:14:55) [ Debug ] : Function: setquest (1 parameter):
(08/27/2018 00:14:55) [ Debug ] : Data: number value=5179
(08/27/2018 00:15:14) [ Error ] : quest_add: Character 151998 already has quest 5179.
(08/27/2018 00:15:14) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/27/2018 00:15:14) [ Debug ] : Function: setquest (1 parameter):
(08/27/2018 00:15:14) [ Debug ] : Data: number value=5179
(08/27/2018 00:21:40) [ Error ] : quest_add: Character 151998 already has quest 5174.
(08/27/2018 00:21:40) [ Debug ] : Source (NPC): Reno#2012hat at moc_para01 (41,169)
(08/27/2018 00:21:40) [ Debug ] : Function: setquest (1 parameter):
(08/27/2018 00:21:40) [ Debug ] : Data: number value=5174
(08/27/2018 00:53:30) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/27/2018 01:38:43) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/27/2018 02:01:00) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not GojekCommand (id=110019291).
(08/27/2018 06:18:04) [ Error ] : buildin_unittalk: Unit with ID '111441597' is not found.
(08/27/2018 06:18:04) [ Error ] : buildin_getunitdata: Unit with ID '111441597' is not found.
(08/27/2018 06:18:04) [ Debug ] : Source (NPC): #crssk1 at 1@xm_d (1,5)
(08/27/2018 06:18:04) [ Error ] : buildin_getunitdata: Unit with ID '111441597' is not found.
(08/27/2018 06:18:04) [ Debug ] : Source (NPC): #crssk2 at 1@xm_d (1,5)
(08/27/2018 06:18:04) [ Error ] : buildin_getunitdata: Unit with ID '111441597' is not found.
(08/27/2018 06:18:04) [ Debug ] : Source (NPC): #crssk3 at 1@xm_d (1,5)
(08/27/2018 06:18:04) [ Error ] : buildin_getunitdata: Unit with ID '111441597' is not found.
(08/27/2018 06:18:04) [ Debug ] : Source (NPC): #crssk4 at 1@xm_d (1,5)
(08/27/2018 08:55:05) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/27/2018 12:13:12) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/27/2018 13:12:17) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/27/2018 14:01:49) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/27/2018 14:26:46) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/27/2018 15:56:28) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Warper (id=110019193).
(08/27/2018 16:34:55) [ Error ] : quest_add: Character 154063 already has quest 11124.
(08/27/2018 16:34:55) [ Debug ] : Source (NPC): Spike at moc_para01 (32,30)
(08/27/2018 16:34:55) [ Debug ] : Function: setquest (1 parameter):
(08/27/2018 16:34:55) [ Debug ] : Data: number value=11124
(08/27/2018 18:51:43) [ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Wolf Roegenburg#ep16lug (id=110015213).
(08/27/2018 19:00:31) [ Error ] : quest_delete: Character 153869 doesn't have quest 2186.
(08/27/2018 19:00:31) [ Debug ] : Source (NPC): High Laphine#grenouille at spl_in01 (30,324)
(08/27/2018 19:00:31) [ Debug ] : Function: erasequest (1 parameter):
(08/27/2018 19:00:31) [ Debug ] : Data: number value=2186
(08/27/2018 19:07:31) [ Debug ] : npc_scriptcont: #ep16_evt_7688 (sd->npc_id=110015132) is not 'Unknown NPC' (id=0).
(08/27/2018 20:14:40) [ Error ] : Server received crash signal! Attempting to save all online characters!
```

**Comment by aleos89** [comment]
Same issue reported in #3402. You can check #3405 for the fix.
