### ISSUE TITLE
Map Server Crash instance.cpp timer.cpp map.cpp

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#3437]
* **rAthena Hash**: da83e61

* **VPS Information**: CentOS Linux release 7.5.1804 (Core) with gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Map Server Crash with Log of instance.cpp timer.cpp map.cpp
  * Result: 

GDB LOG:
```
[root@ragnarok-sg rathena]# gdb map-server core.15831
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/rathena/map-server...done.
[New LWP 15831]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 6, Aborted.
#0  0x00007fcf23efc277 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt full
#0  0x00007fcf23efc277 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fcf23efd968 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fcf23f3ed37 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007fcf23f47499 in _int_free () from /lib64/libc.so.6
No symbol table info available.
#4  0x00000000004cbc20 in deallocate (this=<optimized out>, 
    __p=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/new_allocator.h:125
No locals.
#5  deallocate (__a=..., __n=1, __p=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/alloc_traits.h:462
No locals.
#6  _M_deallocate_node (this=<optimized out>, __n=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/hashtable_policy.h:2086
No locals.
#7  _M_deallocate_nodes (this=<optimized out>, __n=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/hashtable_policy.h:2097
        __tmp = <optimized out>
#8  std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash---Type <return> to continue, or q <return> to quit---
<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear (this=this@entry=0xe4dd48 <map+5451336>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/hashtable.h:2029
No locals.
#9  0x00000000004c908f in clear (this=0xe4dd48 <map+5451336>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/unordered_map.h:845
No locals.
#10 map_delinstancemap (m=1014) at map.cpp:2763
        __FUNCTION__ = "map_delinstancemap"
#11 0x00000000004abf44 in instance_destroy (instance_id=2) at instance.cpp:673
        im = 0x915b80 <instance_data+128>
        sd = 0x0
        pd = 0x7fcf1803d4a4
        gd = 0x0
        cd = 0x0
        i = 0
        type = 2
        now = <optimized out>
        mode = IM_PARTY
        __FUNCTION__ = "instance_destroy"
#12 0x00000000004ac40c in instance_delete_timer (tid=<optimized out>, 
    tick=<optimized out>, id=<optimized out>, data=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at instance.cpp:98
No locals.
#13 0x000000000040adaa in do_timer (tick=<optimized out>) at timer.cpp:370
        tid = 471
        diff = -19
#14 main (argc=<optimized out>, argv=<optimized out>) at core.cpp:367
No locals.
(gdb) 
```

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by ecdarreola** [comment]
Similar with #3413
