### ISSUE TITLE
Server crash with command @mapitem

### ISSUE THREAD

**Issue by van84** [rathena/rathena#3462]
* **rAthena Hash**: 
b4d5f4f

* **Client Date**: 
All client

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
  @mapitem 512 2
Crash!

here some trace log:

```Program received signal SIGSEGV, Segmentation fault.
0x00000000005ff627 in safestrncpy (dst=dst@entry=0x7fffffffd6b0 "\003", src=0x0, n=n@entry=12) at strlib.cpp:376
376                             if( (*d++ = *s++) == '\0' )
#0  0x00000000005ff627 in safestrncpy (dst=dst@entry=0x7fffffffd6b0 "\003", src=0x0, n=n@entry=12) at strlib.cpp:376
#1  0x0000000000570335 in buildin_getmapxy (st=0x7fffeb38bb4c) at script.cpp:14965
#2  0x0000000000542c0d in run_func (st=st@entry=0x7fffeb38bb4c) at script.cpp:3996
#3  0x0000000000547470 in run_script_main (st=0x7fffeb38bb4c) at script.cpp:4271
#4  0x00000000004e3ec4 in npc_do_atcmd_event (sd=0x5b75290, command=0x7fffffffd870 "@mapitem", message=0x7fffffffd970 "512 10", eventname=0x7fffc68964f6 "GMCOMMAND::OnMapItem") at npc.cpp:3726
#5  0x000000000043136c in is_atcommand (fd=fd@entry=9, sd=sd@entry=0x5b75290, message=message@entry=0x7fffffffdd70 "@mapitem 512 10", type=type@entry=1) at atcommand.cpp:10602
#6  0x000000000045a3de in clif_process_message (sd=sd@entry=0x5b75290, whisperFormat=whisperFormat@entry=false, out_name=out_name@entry=0x7fffffffdd50 "bob", out_message=out_message@entry=0x7fffffffdd70 "@mapitem 512 10", out_full_message=out_full_message@entry=0x7fffffffde70 "bob : @mapitem 512 10") at clif.cpp:10084
#7  0x000000000046c1d5 in clif_parse_GlobalMessage (fd=9, sd=0x5b75290) at clif.cpp:10935
#8  0x0000000000461b33 in clif_parse (fd=9) at clif.cpp:20627
#9  0x00000000005f8ccd in do_sockets (next=<optimized out>) at socket.cpp:917
#10 0x00000000004074bb in main (argc=1, argv=0x7fffffffe348) at core.cpp:368
#0  0x00000000005ff627 in safestrncpy (dst=dst@entry=0x7fffffffd6b0 "\003", src=0x0, n=n@entry=12) at strlib.cpp:376
        d = 0x7fffffffd6b0 "\003"
        s = 0x0
        n = 11
        src = 0x0
        dst = 0x7fffffffd6b0 "\003"
#1  0x0000000000570335 in buildin_getmapxy (st=0x7fffeb38bb4c) at script.cpp:14965
        sd = 0x0
        num = <optimized out>
        prefix = <optimized out>
        x = 0
        type = <optimized out>
        mapname = "\003\000\000\000\000\000\000\000czT"
        __FUNCTION__ = "buildin_getmapxy"
        bl = <optimized out>
        name = <optimized out>
        y = 0
#2  0x0000000000542c0d in run_func (st=st@entry=0x7fffeb38bb4c) at script.cpp:3996
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        func = 377
        end_sp = <optimized out>
#3  0x0000000000547470 in run_script_main (st=0x7fffeb38bb4c) at script.cpp:4271
        c = C_FUNC
        cmdcount = 655298
        gotocount = 2044
        sd = <optimized out>
        stack = 0x7fffdf9de8cc
#4  0x00000000004e3ec4 in npc_do_atcmd_event (sd=0x5b75290, command=0x7fffffffd870 "@mapitem", message=0x7fffffffd970 "512 10", eventname=0x7fffc68964f6 "GMCOMMAND::OnMapItem") at npc.cpp:3726
        nd = 0x7fffc6ed32d4
        i = 7
        k = 0
        temp = 0x7fffde63051c '\375' <repeats 24 times>, "p\336b\336\377\177"
        __FUNCTION__ = "npc_do_atcmd_event"
        ev = 0x7fffdc601314
        st = 0x7fffeb38bb4c
        j = 2
#5  0x000000000043136c in is_atcommand (fd=fd@entry=9, sd=sd@entry=0x5b75290, message=message@entry=0x7fffffffdd70 "@mapitem 512 10", type=type@entry=1) at atcommand.cpp:10602
        binding = 0x7fffc68964c4
        command = "@mapitem", '\000' <repeats 247 times>
        params = "512 10", '\000' <repeats 249 times>
        atcmd_msg = "@mapitem 512 10\000_\000\000\000`\000\000\000 I\240\366\377\177\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\245\000\000\000\000\000\000\000\220R\267\005\000\000\000\000\t\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000p\335\377\377\377\177\000\000P\335\377\377\377\177\000\000H\370Q\303\377\177\000\000=\374t\366\377\177\000\000\001\000\000\000\000\000\000\000\060\000\000\000\060\000\000\000\310\334\377\377\377\177\000\000\000\334\377\377\377\177\000\000\000\000\000\000\000\000\000\000LSK\303\377\177\000\000\264m\211\306\377\177\000\000\001\000\000\000\000\000\000\000P\335\377\377\377\177\000\000>\373k\000\000\000\000\000\001\000\000\000\000\000\000\000"...
        info = <optimized out>
        __FUNCTION__ = "is_atcommand"
        output = "p\336\377\377\377\177\000\000\260\332\377\377\377\177\000\000p\336\377\377\377\177\000\000AAg\000\000\000\000\000\350\333\377\377\377\177\000\000\001\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\344\374t\366\377\177\000\000\001\200\255\373\000\000\000\000p\336\377\377\377\177\000\000p\336\377\377\377\177\000\000p\336\377\377\377\177\000\000p\336\377\377\377\177\000\000\213\336\377\377\377\177\000\000\377\377\377\377\377\377\377\377p\336\377\377\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 44 times>, "\004", '\000' <repeats 43 times>...
        ssd = 0x5b75290
        is_atcommand = <optimized out>
#6  0x000000000045a3de in clif_process_message (sd=sd@entry=0x5b75290, whisperFormat=whisperFormat@entry=false, out_name=out_name@entry=0x7fffffffdd50 "bob", out_message=out_message@entry=0x7fffffffdd70 "@mapitem 512 10", out_full_message=out_full_message@entry=0x7fffffffde70 "bob : @mapitem 512 10") at clif.cpp:10084
        seperator = 0x6bfb3e " : "
        packetLength = <optimized out>
        message = <optimized out>
        messageLength = 16
        fd = 9
        info = <optimized out>
        inputLength = <optimized out>
        input = 0x7fffc351f848 "bob : @mapitem 512 10s critical for the game"
        name = 0x7fffc351f848 "bob : @mapitem 512 10s critical for the game"
        nameLength = <optimized out>
#7  0x000000000046c1d5 in clif_parse_GlobalMessage (fd=9, sd=0x5b75290) at clif.cpp:10935
        message = "@mapitem 512 10\000\000\000\000\000\000\000\000\000\060\000\000\000\060\000\000\000\300\336\377\377\377\177\000\000\000\336\377\377\377\177\000\000\000\000\000\000\000\000\000\000\203\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\n\000\000\000\000\000\000\000\026ɷ\241\000\000\000\000ܔQ\303\377\177\000\000\066\200K\000\000\000\000\000\006\000\000\000\000\000\000\000 \000\000\000\060\000\000\000\300\336\377\377\377\177\000\000\000\336\377\377\377\177\000\000\001\000\377", '\000' <repeats 29 times>, "ܔQ\303\377\177\000\000\350\336\377\377\377\177\000\000\\\231Q\303\377\177\000\000.\230\264"...
        length = <optimized out>
        __FUNCTION__ = "clif_parse_GlobalMessage"
        name = "bob\000\000\000\f\000\000\000\022\000\000\000\000\000\000"
        output = "bob : @mapitem 512 10\000\377\177\000\000\000\000\000\000.E\217\006\374\016\203\304\377\177\000\000\001\000\000\000\000\000\000\000\016\204K\000\000\000\000\000\001\000\000\000\000\000\000\000\267\357L\000\000\000\000\000\004\000\000\000\t\000\000\000`\000K\000\001\000\000\000\000\000\000\000\f\000\000\000\b\000\000\000\r\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\004\000\000\000\000\r\000\000\000\250\065N\000\000\000\000\000?J\002\000\000\000\000\000\060\000\000\000\060\000\000\000p\340\377\377\377\177\000\000\240\337\377\377\377\177\000\000 \266\247\000\000\000\000\000\374\016\203\304\377\177\000\000\260\340\377\377\377\177\000\000\000\000\000\000\000\000\000\000"...
#8  0x0000000000461b33 in clif_parse (fd=9) at clif.cpp:20627
        cmd = <optimized out>
        packet_len = 31
        sd = 0x5b75290
        pnum = 0
#9  0x00000000005f8ccd in do_sockets (next=<optimized out>) at socket.cpp:917
        rfd = {fds_bits = {512, 0 <repeats 63 times>}}
        timeout = {tv_sec = 0, tv_usec = 19}
        ret = <optimized out>
        i = 9
#10 0x00000000004074bb in main (argc=1, argv=0x7fffffffe348) at core.cpp:368
        next = <optimized out>
  Id   Target Id         Frame
* 1    Thread 0x7ffff7fec780 (LWP 18089) "map-server" 0x00000000005ff627 in safestrncpy (dst=dst@entry=0x7fffffffd6b0 "\003", src=0x0, n=n@entry=12) at strlib.cpp:376

Thread 1 (Thread 0x7ffff7fec780 (LWP 18089)):
#0  0x00000000005ff627 in safestrncpy (dst=dst@entry=0x7fffffffd6b0 "\003", src=0x0, n=n@entry=12) at strlib.cpp:376
        d = 0x7fffffffd6b0 "\003"
        s = 0x0
        n = 11
        src = 0x0
        dst = 0x7fffffffd6b0 "\003"
#1  0x0000000000570335 in buildin_getmapxy (st=0x7fffeb38bb4c) at script.cpp:14965
        sd = 0x0
        num = <optimized out>
        prefix = <optimized out>
        x = 0
        type = <optimized out>
        mapname = "\003\000\000\000\000\000\000\000czT"
        __FUNCTION__ = "buildin_getmapxy"
        bl = <optimized out>
        name = <optimized out>
        y = 0
#2  0x0000000000542c0d in run_func (st=st@entry=0x7fffeb38bb4c) at script.cpp:3996
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        func = 377
        end_sp = <optimized out>
#3  0x0000000000547470 in run_script_main (st=0x7fffeb38bb4c) at script.cpp:4271
        c = C_FUNC
        cmdcount = 655298
        gotocount = 2044
        sd = <optimized out>
        stack = 0x7fffdf9de8cc
#4  0x00000000004e3ec4 in npc_do_atcmd_event (sd=0x5b75290, command=0x7fffffffd870 "@mapitem", message=0x7fffffffd970 "512 10", eventname=0x7fffc68964f6 "GMCOMMAND::OnMapItem") at npc.cpp:3726
        nd = 0x7fffc6ed32d4
        i = 7
        k = 0
        temp = 0x7fffde63051c '\375' <repeats 24 times>, "p\336b\336\377\177"
        __FUNCTION__ = "npc_do_atcmd_event"
        ev = 0x7fffdc601314
        st = 0x7fffeb38bb4c
        j = 2
#5  0x000000000043136c in is_atcommand (fd=fd@entry=9, sd=sd@entry=0x5b75290, message=message@entry=0x7fffffffdd70 "@mapitem 512 10", type=type@entry=1) at atcommand.cpp:10602
        binding = 0x7fffc68964c4
        command = "@mapitem", '\000' <repeats 247 times>
        params = "512 10", '\000' <repeats 249 times>
        atcmd_msg = "@mapitem 512 10\000_\000\000\000`\000\000\000 I\240\366\377\177\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\245\000\000\000\000\000\000\000\220R\267\005\000\000\000\000\t\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000p\335\377\377\377\177\000\000P\335\377\377\377\177\000\000H\370Q\303\377\177\000\000=\374t\366\377\177\000\000\001\000\000\000\000\000\000\000\060\000\000\000\060\000\000\000\310\334\377\377\377\177\000\000\000\334\377\377\377\177\000\000\000\000\000\000\000\000\000\000LSK\303\377\177\000\000\264m\211\306\377\177\000\000\001\000\000\000\000\000\000\000P\335\377\377\377\177\000\000>\373k\000\000\000\000\000\001\000\000\000\000\000\000\000"...
        info = <optimized out>
        __FUNCTION__ = "is_atcommand"
        output = "p\336\377\377\377\177\000\000\260\332\377\377\377\177\000\000p\336\377\377\377\177\000\000AAg\000\000\000\000\000\350\333\377\377\377\177\000\000\001\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\344\374t\366\377\177\000\000\001\200\255\373\000\000\000\000p\336\377\377\377\177\000\000p\336\377\377\377\177\000\000p\336\377\377\377\177\000\000p\336\377\377\377\177\000\000\213\336\377\377\377\177\000\000\377\377\377\377\377\377\377\377p\336\377\377\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 44 times>, "\004", '\000' <repeats 43 times>...
        ssd = 0x5b75290
        is_atcommand = <optimized out>
#6  0x000000000045a3de in clif_process_message (sd=sd@entry=0x5b75290, whisperFormat=whisperFormat@entry=false, out_name=out_name@entry=0x7fffffffdd50 "bob", out_message=out_message@entry=0x7fffffffdd70 "@mapitem 512 10", out_full_message=out_full_message@entry=0x7fffffffde70 "bob : @mapitem 512 10") at clif.cpp:10084
        seperator = 0x6bfb3e " : "
        packetLength = <optimized out>
        message = <optimized out>
        messageLength = 16
        fd = 9
        info = <optimized out>
        inputLength = <optimized out>
        input = 0x7fffc351f848 "bob : @mapitem 512 10s critical for the game"
        name = 0x7fffc351f848 "bob : @mapitem 512 10s critical for the game"
        nameLength = <optimized out>
#7  0x000000000046c1d5 in clif_parse_GlobalMessage (fd=9, sd=0x5b75290) at clif.cpp:10935
        message = "@mapitem 512 10\000\000\000\000\000\000\000\000\000\060\000\000\000\060\000\000\000\300\336\377\377\377\177\000\000\000\336\377\377\377\177\000\000\000\000\000\000\000\000\000\000\203\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\n\000\000\000\000\000\000\000\026ɷ\241\000\000\000\000ܔQ\303\377\177\000\000\066\200K\000\000\000\000\000\006\000\000\000\000\000\000\000 \000\000\000\060\000\000\000\300\336\377\377\377\177\000\000\000\336\377\377\377\177\000\000\001\000\377", '\000' <repeats 29 times>, "ܔQ\303\377\177\000\000\350\336\377\377\377\177\000\000\\\231Q\303\377\177\000\000.\230\264"...
        length = <optimized out>
        __FUNCTION__ = "clif_parse_GlobalMessage"
        name = "bob\000\000\000\f\000\000\000\022\000\000\000\000\000\000"
        output = "bob : @mapitem 512 10\000\377\177\000\000\000\000\000\000.E\217\006\374\016\203\304\377\177\000\000\001\000\000\000\000\000\000\000\016\204K\000\000\000\000\000\001\000\000\000\000\000\000\000\267\357L\000\000\000\000\000\004\000\000\000\t\000\000\000`\000K\000\001\000\000\000\000\000\000\000\f\000\000\000\b\000\000\000\r\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\004\000\000\000\000\r\000\000\000\250\065N\000\000\000\000\000?J\002\000\000\000\000\000\060\000\000\000\060\000\000\000p\340\377\377\377\177\000\000\240\337\377\377\377\177\000\000 \266\247\000\000\000\000\000\374\016\203\304\377\177\000\000\260\340\377\377\377\177\000\000\000\000\000\000\000\000\000\000"...
#8  0x0000000000461b33 in clif_parse (fd=9) at clif.cpp:20627
        cmd = <optimized out>
        packet_len = 31
        sd = 0x5b75290
        pnum = 0
#9  0x00000000005f8ccd in do_sockets (next=<optimized out>) at socket.cpp:917
        rfd = {fds_bits = {512, 0 <repeats 63 times>}}
        timeout = {tv_sec = 0, tv_usec = 19}
        ret = <optimized out>
        i = 9
#10 0x00000000004074bb in main (argc=1, argv=0x7fffffffe348) at core.cpp:368
        next = <optimized out>
```

**Comment by cydh** [comment]
rathena doesn't have mapitem command

**Comment by jezznar** [comment]
@van84 official atcommand list can be found here: https://raw.githubusercontent.com/rathena/rathena/master/doc/atcommands.txt
