### ISSUE TITLE
CRASH on latest version

### ISSUE THREAD

**Issue by van84** [rathena/rathena#3543]
474cb7d900a7f2e1b570a823127905def9a7bc0a

* **Client Date**: 

2015

* **Server Mode**: 
```
4915                    status->rhw.atk = status_calc_watk(bl, sc, b_status->rhw.atk);
#0  status_calc_bl_main (bl=bl@entry=0x7fffc3519474, flag=flag@entry=1024) at status.cpp:4915
#1  0x00005555557520bb in status_calc_bl_ (bl=0x7fffc3519474, flag=SCB_WATK, opt=<optimized out>) at status.cpp:5334
#2  0x000055555574216e in status_change_end_ (bl=bl@entry=0x7fffc3519474, type=<optimized out>, tid=tid@entry=-1, file=file@entry=0x5555557d63f8 "status.cpp", line=line@entry=12047) at status.cpp:12836
#3  0x0000555555744a96 in status_change_clear (bl=bl@entry=0x7fffc3519474, type=type@entry=1) at status.cpp:12047
#4  0x000055555575dc0d in unit_free (bl=0x7fffc3519474, clrtype=clrtype@entry=CLR_TELEPORT) at unit.cpp:3451
#5  0x000055555562f997 in mob_timer_delete (tid=13273, tick=<optimized out>, id=<optimized out>, data=<optimized out>) at mob.cpp:2215
#6  0x0000555555572f3a in main ()
#0  status_calc_bl_main (bl=bl@entry=0x7fffc3519474, flag=flag@entry=1024) at status.cpp:4915
        b_status = 0x14c
        status = 0x7fffc3519890
        sc = <optimized out>
        sd = 0x0
        temp = <optimized out>
#1  0x00005555557520bb in status_calc_bl_ (bl=0x7fffc3519474, flag=SCB_WATK, opt=<optimized out>) at status.cpp:5334
        b_status = {hp = 1083240, sp = 6144, max_hp = 1083240, max_sp = 6144, str = 393, agi = 319, vit = 190, int_ = 186, dex = 307, luk = 322, eatk = 0, batk = 0, matk_min = 862, matk_max = 1555, speed = 150, amotion = 70, adelay = 140, dmotion = 400, mode = (MD_CANMOVE | MD_AGGRESSIVE | MD_ASSIST | MD_CASTSENSOR_IDLE | MD_NORANDOM_WALK | MD_NOCAST_SKILL | MD_CANATTACK | MD_CASTSENSOR_CHASE | MD_CHANGECHASE | MD_CHANGETARGET_MELEE | MD_CHANGETARGET_CHASE | MD_RANDOMTARGET | unknown: 256), hit = 577, flee = 589, cri = 0, flee2 = 0, def2 = 190, mdef2 = 281, aspd_rate = 1000, def = 25 '\031', mdef = 49 '1', def_ele = 0 '\000', ele_lv = 1 '\001', size = 1 '\001', race = 10 '\n', class_ = 0 '\000', rhw = {atk = 231, atk2 = 278, range = 1, ele = 0 '\000'}, lhw = {atk = 231, atk2 = 333, range = 1, ele = 0 '\000'}}
        status = 0x7fffc3519890
#2  0x000055555574216e in status_change_end_ (bl=bl@entry=0x7fffc3519474, type=<optimized out>, tid=tid@entry=-1, file=file@entry=0x5555557d63f8 "status.cpp", line=line@entry=12047) at status.cpp:12836
        sd = 0x0
        sc = <optimized out>
        sce = 0x55555a6b1c84
        status = <optimized out>
        vd = <optimized out>
        opt_flag = <optimized out>
        calc_flag = SCB_WATK
        __FUNCTION__ = "status_change_end_"
#3  0x0000555555744a96 in status_change_clear (bl=bl@entry=0x7fffc3519474, type=type@entry=1) at status.cpp:12047
        sc = <optimized out>
        i = 68
#4  0x000055555575dc0d in unit_free (bl=0x7fffc3519474, clrtype=clrtype@entry=CLR_TELEPORT) at unit.cpp:3451
        ud = <optimized out>
        __FUNCTION__ = "unit_free"
#5  0x000055555562f997 in mob_timer_delete (tid=13273, tick=<optimized out>, id=<optimized out>, data=<optimized out>) at mob.cpp:2215
        bl = <optimized out>
        md = <optimized out>
#6  0x0000555555572f3a in main ()
No symbol table info available.
  Id   Target Id         Frame
* 1    Thread 0x7ffff7feb340 (LWP 29251) "map-server" 0x000055555562f997 in mob_timer_delete (tid=13273, tick=<optimized out>, id=<optimized out>, data=<optimized out>) at mob.cpp:2215

Thread 1 (Thread 0x7ffff7feb340 (LWP 29251)):
#0  status_calc_bl_main (bl=bl@entry=0x7fffc3519474, flag=flag@entry=1024) at status.cpp:4915
        b_status = 0x14c
        status = 0x7fffc3519890
        sc = <optimized out>
        sd = 0x0
        temp = <optimized out>
#1  0x00005555557520bb in status_calc_bl_ (bl=0x7fffc3519474, flag=SCB_WATK, opt=<optimized out>) at status.cpp:5334
        b_status = {hp = 1083240, sp = 6144, max_hp = 1083240, max_sp = 6144, str = 393, agi = 319, vit = 190, int_ = 186, dex = 307, luk = 322, eatk = 0, batk = 0, matk_min = 862, matk_max = 1555, speed = 150, amotion = 70, adelay = 140, dmotion = 400, mode = (MD_CANMOVE | MD_AGGRESSIVE | MD_ASSIST | MD_CASTSENSOR_IDLE | MD_NORANDOM_WALK | MD_NOCAST_SKILL | MD_CANATTACK | MD_CASTSENSOR_CHASE | MD_CHANGECHASE | MD_CHANGETARGET_MELEE | MD_CHANGETARGET_CHASE | MD_RANDOMTARGET | unknown: 256), hit = 577, flee = 589, cri = 0, flee2 = 0, def2 = 190, mdef2 = 281, aspd_rate = 1000, def = 25 '\031', mdef = 49 '1', def_ele = 0 '\000', ele_lv = 1 '\001', size = 1 '\001', race = 10 '\n', class_ = 0 '\000', rhw = {atk = 231, atk2 = 278, range = 1, ele = 0 '\000'}, lhw = {atk = 231, atk2 = 333, range = 1, ele = 0 '\000'}}
        status = 0x7fffc3519890
#2  0x000055555574216e in status_change_end_ (bl=bl@entry=0x7fffc3519474, type=<optimized out>, tid=tid@entry=-1, file=file@entry=0x5555557d63f8 "status.cpp", line=line@entry=12047) at status.cpp:12836
        sd = 0x0
        sc = <optimized out>
        sce = 0x55555a6b1c84
        status = <optimized out>
        vd = <optimized out>
        opt_flag = <optimized out>
        calc_flag = SCB_WATK
        __FUNCTION__ = "status_change_end_"
#3  0x0000555555744a96 in status_change_clear (bl=bl@entry=0x7fffc3519474, type=type@entry=1) at status.cpp:12047
        sc = <optimized out>
        i = 68
#4  0x000055555575dc0d in unit_free (bl=0x7fffc3519474, clrtype=clrtype@entry=CLR_TELEPORT) at unit.cpp:3451
        ud = <optimized out>
        __FUNCTION__ = "unit_free"
#5  0x000055555562f997 in mob_timer_delete (tid=13273, tick=<optimized out>, id=<optimized out>, data=<optimized out>) at mob.cpp:2215
        bl = <optimized out>
        md = <optimized out>
```

**Comment by van84** [comment]
lines may be wrong, we add some comments in the code

**Comment by aleos89** [comment]
Can you provide a little more information: Pre-re or Renewal? Have you merged any rAthena PR's to your local copy? How did you produce the crash?

**Comment by Lemongrass3110** [comment]
User does not know how to reproduce it himself.
Neither do we.
