### ISSUE TITLE
Map Server Crash

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#3576]
* **rAthena Hash**: a12f1ce

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Map Server Log**: 

```
(10/14/2018 20:58:16) [ Error ] : map_addinstancemap failed. map_num(1500) > map_max(1500)
(10/14/2018 20:58:16) [ Error ] : instance_addmap: No maps added to instance 'Sealed Catacomb' (1).
(10/14/2018 20:58:48) [ Error ] : npc_touch_areanpc : stray NPC cell/NPC not found in the block on coordinates '0011@cata',139,218
(10/14/2018 20:58:48) [ Error ] : npc_touch_areanpc : stray NPC cell/NPC not found in the block on coordinates '0011@cata',139,219
(10/14/2018 20:58:49) [ Error ] : npc_touch_areanpc : stray NPC cell/NPC not found in the block on coordinates '0011@cata',140,218
(10/14/2018 21:01:09) [ Error ] : map_addinstancemap failed. map_num(1500) > map_max(1500)
(10/14/2018 21:01:09) [ Error ] : instance_addmap: Failed to create initial map for instance 'Faceworm's Nest' (2).
(10/14/2018 21:01:37) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012401' (flag=0).
(10/14/2018 21:01:37) [ Debug ] : (map_mapname2mapid) mapindex_name2id: Map "" not found in index list!
(10/14/2018 21:01:44) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012400' (flag=0).
(10/14/2018 21:01:46) [ Error ] : npc_event: event not found [dup_2_110012401::OnMyMobDead]
(10/14/2018 21:01:54) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012400' (flag=0).
(10/14/2018 21:01:59) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012400' (flag=0).
(10/14/2018 21:02:04) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012401' (flag=0).
(10/14/2018 21:02:44) [ Error ] : buildin_instance_npcname: Invalid instance NPC (instance_id: 0, NPC name: "Suspicious Mound#8".)
(10/14/2018 21:02:44) [ Debug ] : Source (NPC): Suspicious Mound#8 at 1@face (76,241)
(10/14/2018 21:02:49) [ Error ] : buildin_instance_npcname: Invalid instance NPC (instance_id: 0, NPC name: "Suspicious Mound#9".)
(10/14/2018 21:02:49) [ Debug ] : Source (NPC): Suspicious Mound#9 at 1@face (79,274)
(10/14/2018 21:03:31) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012396' (flag=0).
(10/14/2018 21:03:33) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012400' (flag=0).
(10/14/2018 21:03:36) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012465' (flag=4).
(10/14/2018 21:03:37) [ Error ] : npc_enable: Attempted to hide a non-existing NPC 'dup_2_110012398' (flag=0).
(10/14/2018 21:03:37) [ Warning ] : script:get_val: cannot access instance variable ''map_name$', defaulting to ""
(10/14/2018 21:03:37) [ Debug ] : (map_mapname2mapid) mapindex_name2id: Map "" not found in index list!
(10/14/2018 21:03:37) [ Error ] : Server received crash signal! Attempting to save all online characters!

```

* **GDB Log**: 
```
(gdb) bt full
#0  0x00000000004c5c42 in map_searchrandfreecell (m=m@entry=-1, 
    x=x@entry=0x7ffd5b25b44c, y=y@entry=0x7ffd5b25b448, stack=stack@entry=0)
    at map.cpp:1593
        free_cell = 0
        i = -1
        j = <optimized out>
        free_cells = {{1529197504, 32765}, {0, 0}, {111584072, 0}, {6598080, 
            0}, {1529197696, 32765}, {0, 0}, {12, 0}, {12, 0}, {-1055977780, 
            32704}}
#1  0x00000000004c5e14 in map_addflooritem (item=item@entry=0x7ffd5b25b4b0, 
    amount=amount@entry=1, m=<optimized out>, x=x@entry=27, y=y@entry=290, 
    first_charid=first_charid@entry=0, second_charid=0, third_charid=0, 
    flags=4, mob_id=0) at map.cpp:1803
        r = <optimized out>
        fitem = 0x0
        __FUNCTION__ = "map_addflooritem"
#2  0x00000000005682c9 in buildin_makeitem (st=0x7fc0c10f0ecc)
    at script.cpp:7584
        nameid = 721
        amount = 1
        x = 27
        y = 290
        mapname = 0x690224 ""
---Type <return> to continue, or q <return> to quit---
        m = <optimized out>
        item_tmp = {id = 0, nameid = 721, amount = 0, equip = 0, 
          identify = 1 '\001', refine = 0 '\000', attribute = 0 '\000', 
          card = {0, 0, 0, 0}, option = {{id = 0, value = 0, 
              param = 0 '\000'}, {id = 0, value = 0, param = 0 '\000'}, {
              id = 0, value = 0, param = 0 '\000'}, {id = 0, value = 0, 
              param = 0 '\000'}, {id = 0, value = 0, param = 0 '\000'}}, 
          expire_time = 0, favorite = 0 '\000', bound = 0 '\000', 
          unique_id = 0}
        data = <optimized out>
        __FUNCTION__ = "buildin_makeitem"
#3  0x000000000054a19d in run_func (st=st@entry=0x7fc0c10f0ecc)
    at script.cpp:3995
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        end_sp = <optimized out>
        func = 107
#4  0x000000000054e630 in run_script_main (st=0x7fc0c10f0ecc)
    at script.cpp:4270
        cmdcount = 655150
        gotocount = 2042
        sd = <optimized out>
---Type <return> to continue, or q <return> to quit---
        stack = 0x7fc0bd48d7dc
#5  0x00000000004e0d9c in npc_timerevent (tid=194, tick=2199288967, 
    id=110012465, data=106161156) at npc.cpp:640
        old_rid = 0
        old_timer = 0
        old_tick = 2199287967
        nd = 0x7fc0b5e99ad4
        te = 0x7fc0b6148944
        ted = 0x653e404
        sd = 0x0
#6  0x000000000040afc8 in do_timer (tick=<optimized out>) at timer.cpp:370
        tid = 194
        diff = -8
#7  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:367
No locals.
(gdb) 

```

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
This was fixed in #3539. Please make sure you update accordingly.
