### ISSUE TITLE
Map server crash ep. 16.1 [reproducible]

### ISSUE THREAD

**Issue by Joao1905** [rathena/rathena#3652]
* **rAthena Hash**: 8c9b7a

* **Client Date**: 20180530

* **Server Mode**: Renewal

* **Description of Issue**: Map-server crashes on custom/newer instances, including banquet of heroes: ritual of blessing and room of consciousness.
  * Result: Whenever a player enters a custom/new instance for the second time, the map server crashes.
  * Expected Result: Instance is created normally, and players get warped.
  * How to Reproduce: 

> 
> • Have a clean rAthena installation of the specified Hash.
> •Add the following to re/instance_db: `50,TestInst,3600,300,pay_dun00,33,166`
> • Despite of working similarly on some custom or new instances, we will use the following testing script for agility purposes: 
> ```
> prontera,158,185,4	script	Tester	870,{
> 	instance_create("TestInst");
> 	instance_enter("TestInst",-1,-1);
> }
> ```
> • Start server, create a party, click on npc. You will enter the instance normally.
> • Warp back to prontera.
> • Leave party. Create a new party.
> • Click on npc again to create and enter in a new instance.
> • Map server crashes as soon as you get warped.

  * Official Information: N/A.
  

* **Modifications that may affect results**: The map crash depends solely on the instance entry map. Switching to any existing instance map (1@spa for example) will not result in a map crash.
  
  

* Additional Information: If you try using any duplicate/custom map as your instance entry map, it should crash as well. There are a lot of other maps that also causes the map server crash. I'm not sure this is related to the Issue I just adressed, but instance destroy also causes a map-server crash.

* GDB debug result:
```
Program received signal SIGSEGV, Segmentation fault.
std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (__code=27, __k=@0x7fffffffe39e: 27, __n=5,
    this=0x55555604e388 <map+5962056>)
    at /usr/include/c++/5/bits/hashtable.h:1421
1421          for (__node_type* __p = static_cast<__node_type*>(__prev_p->_M_nxt);;
(gdb) bt full
#0  std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (__code=27, __k=@0x7fffffffe39e: 27, __n=5,
    this=0x55555604e388 <map+5962056>)
    at /usr/include/c++/5/bits/hashtable.h:1421
        __p = <optimized out>
        __prev_p = 0xf7000006
        __prev_p = <optimized out>
        __p = <optimized out>
#1  std::_Hashtable<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node (__c=27, __key=@0x7fffffffe39e: 27, __bkt=5,
    this=0x55555604e388 <map+5962056>)
    at /usr/include/c++/5/bits/hashtable.h:632
        __before_n = <optimized out>
        __before_n = <optimized out>
#2  std::__detail::_Map_base<short, std::pair<short const, int>, std::allocator<std::pair<short const, int> >, std::__detail::_Select1st, std::equal_to<short>, std::hash<short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ran---Type <return> to continue, or q <return> to quit---
ged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[] (
    this=this@entry=0x55555604e388 <map+5962056>, __k=@0x7fffffffe39e: 27,
    __k@entry=@0x7fffffffe39e: 0)
    at /usr/include/c++/5/bits/hashtable_policy.h:618
        __h = 0x55555604e388 <map+5962056>
        __code = 27
        __n = 5
        __p = <optimized out>
#3  0x0000555555610bce in std::unordered_map<short, int, std::hash<short>, std::equal_to<short>, std::allocator<std::pair<short const, int> > >::operator[] (
    __k=@0x7fffffffe39e: 27, this=0x55555604e388 <map+5962056>)
    at /usr/include/c++/5/bits/unordered_map.h:672
No locals.
#4  clif_parse_LoadEndAck (fd=<optimized out>, sd=0x55555ae634b0)
    at clif.cpp:10456
        guild_notice = false
        mapdata = 0x55555604e340 <map+5961984>
#5  0x00005555555d9265 in clif_parse (fd=<optimized out>) at clif.cpp:21338
        cmd = <optimized out>
        packet_len = 2
        sd = <optimized out>
        pnum = 0
---Type <return> to continue, or q <return> to quit---
#6  0x0000555555573db5 in do_sockets (next=<optimized out>) at socket.cpp:1304
        rfd = {fds_bits = {256, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 50054}
        ret = <optimized out>
        i = 8
        rfd = <optimized out>
        timeout = <optimized out>
        ret = <optimized out>
        i = <optimized out>
        __d = <optimized out>
#7  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:368
        next = <optimized out>
```
* Chunk of code that is apparently causing the problem:
File: `clif.cpp`
```
if(!pc_isinvisible(sd) && mapdata->flag[MF_PVP]) {
        if(!battle_config.pk_mode) { // remove pvp stuff for pk_mode [Valaris]
            if (!mapdata->flag[MF_PVP_NOCALCRANK])
                sd->pvp_timer = add_timer(gettick()+200, pc_calc_pvprank_timer, sd->bl.id, 0);
            sd->pvp_rank = 0;
            sd->pvp_lastusers = 0;
            sd->pvp_point = 5;
            sd->pvp_won = 0;
            sd->pvp_lost = 0;
        }
        clif_map_property(&sd->bl, MAPPROPERTY_FREEPVPZONE, SELF);
    } else if(sd->duel_group) // set flag, if it's a duel [LuzZza]
        clif_map_property(&sd->bl, MAPPROPERTY_FREEPVPZONE, SELF);
    else if (mapdata->flag[MF_GVG_DUNGEON]) //Line 10456. GDB points to here.
        clif_map_property(&sd->bl, MAPPROPERTY_FREEPVPZONE, SELF); //TODO: Figure out the real packet to send here.
    else if( mapdata_flag_gvg(mapdata) )
        clif_map_property(&sd->bl, MAPPROPERTY_AGITZONE, SELF);
    else
        clif_map_property(&sd->bl, MAPPROPERTY_NOTHING, SELF);
```
  Line: `else if (mapdata->flag[MF_GVG_DUNGEON]) //Line 10456. GDB points to here.`

**Comment by Victor214** [comment]
After going over multiple issues and pull request, apparently applying the following in order solves the issue:

- https://github.com/rathena/rathena/pull/3405
- https://github.com/rathena/rathena/pull/3405/commits/f3332424ddf66ea71a8df078a4682c8d79c44f2b
- https://github.com/rathena/rathena/commit/ae7cb65a969ffea23e9b36a5820ce952c6720e60

Relates Issues : 

- https://github.com/rathena/rathena/issues/3432
- https://github.com/rathena/rathena/issues/3402

**Comment by aleos89** [comment]
Just update to the current master and you should be fine. This was fixed some time ago as @Victor214 has shown. The main problem was because the [array size wasn't reserved](https://github.com/rathena/rathena/pull/3405/files#diff-961e53ea1620d191d3df691cbcf3e602R3547).
