### ISSUE TITLE
Unable to restore stack! Double continuation!

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#3835]
* **rAthena Hash**: 79766cd99eebbc507c82f1900df60e909e46a23e

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-renewal

* **Description of Issue**: 
```
[Warning]: Unable to restore stack! Double continuation!
[Debug]: Previous script (lost):
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)
[Debug]: Current script:
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)

Program received signal SIGSEGV, Segmentation fault.
0x00005555556b6bed in pop_stack (st=st@entry=0x7fffeca07b54, start=0, end=0)
    at script.cpp:3398
3398            struct script_stack* stack = st->stack;
(gdb) bt full
#0  0x00005555556b6bed in pop_stack (st=st@entry=0x7fffeca07b54, start=0,
    end=0) at script.cpp:3398
        stack = 0x0
        data = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "pop_stack"
#1  0x00005555556b7ab2 in run_func (st=st@entry=0x7fffeca07b54)
    at script.cpp:4007
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        end_sp = <optimized out>
        func = 50
#2  0x00005555556bc800 in run_script_main (st=0x7fffeca07b54)
    at script.cpp:4270
        c = <optimized out>
        cmdcount = 655339
        gotocount = 2047
        sd = <optimized out>
        stack = 0x7fffe78ceb1c
#3  0x000055555564b7a8 in npc_scriptcont(map_session_data*, int, bool) ()
No symbol table info available.
#4  0x00005555555d0905 in clif_parse (fd=8) at clif.cpp:20990
        cmd = <optimized out>
        packet_len = 2
        sd = <optimized out>
        pnum = 0
        cmd2 = 21845
#5  0x00005555555749d5 in main ()
No symbol table info available.
```
This only happens today. after i applied this PR https://github.com/rathena/rathena/pull/3831 which im not sure if its connected.

Edit ---
Yup. reverted back without the PR and everything works fine.

**Comment by aleos89** [comment]
I'll go ahead and close this since @Lemongrass3110 fixed it in the PR.
