### ISSUE TITLE
Map Server Crash - CELL_SHOOTABLE

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4032]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/42810ad44ae8eb430e7de603daff24cec19dd4b0

* **Client Date**: 
20180620

* **Server Mode**: 
RE

* **Description of Issue**: 
  * Result: When using this script within the instance a random crash mapserver occurs.
Crash map-server:
```
Program received signal SIGSEGV, Segmentation fault.
map_setcell (m=Unhandled dwarf expression opcode 0xf3
) at map.cpp:3279
3279			case CELL_SHOOTABLE:     mapdata->cell[j].shootable = flag;     break;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 mysql-libs-5.1.73-8.el6_8.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 openssl-1.0.1e-57.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
(gdb) bt full
#0  map_setcell (m=Unhandled dwarf expression opcode 0xf3
) at map.cpp:3279
        j = 6915
#1  0x0000000000529df4 in map_iwall_remove (wall_name=Unhandled dwarf expression opcode 0xf3
) at map.cpp:3417
        iwall = 0x7fffd9834bb4
        i = 0
        x1 = 95
        y1 = 31
#2  0x00000000005b86d7 in buildin_delwall (st=0x7fffedd6b6c4)
    at script.cpp:14078
        name = <value optimized out>
#3  0x00000000005b556d in run_func (st=0x7fffedd6b6c4) at script.cpp:3995
        data = <value optimized out>
        i = <value optimized out>
        start_sp = <value optimized out>
        end_sp = <value optimized out>
        func = 20447
#4  0x00000000005b9dc0 in run_script_main (st=0x7fffedd6b6c4)
    at script.cpp:4270
        cmdcount = 655342
        gotocount = 2048
        sd = <value optimized out>
        stack = 0x7fffe9f986ac
#5  0x00000000005430bf in npc_event_do_sub(DBKey, DBData *, typedef __va_list_tag __va_list_tag *) (key=..., data=0x7570138, ap=0x7fffffffd310) at npc.cpp:433
        p = 0x7fffd9acab24 "dup_5_110033776::OnDisable"
        ev = 0x7fffd9348e24
        c = 0x7fffffffd46c
        rid = 0
        name = 0x7fffd7f8aaa4 "dup_5_110033776::OnDisable"
        __FUNCTION__ = "npc_event_do_sub"
#6  0x000000000068a78c in db_obj_vforeach (self=0x5ceeda8, 
    func=0x542ee5 <npc_event_do_sub(DBKey, DBData *, typedef __va_list_tag __va_list_tag *)>, args=0x7fffffffd370) at db.cpp:2040
        argscopy = void
        db = 0x5ceeda8
        sum = 0
        node = 0x7570118
        parent = <value optimized out>
#7  0x0000000000688279 in db_obj_foreach (self=Unhandled dwarf expression opcode 0xf3
) at db.cpp:2086
        args = void
#8  0x000000000054316d in npc_event_do_id (
    name=0x7fffd7f8aaa4 "dup_5_110033776::OnDisable", rid=0) at npc.cpp:446
        c = 0
#9  0x000000000054318f in npc_event_do (
    name=0x7fffd7f8aaa4 "dup_5_110033776::OnDisable") at npc.cpp:453
No locals.
#10 0x00000000005b7b4a in buildin_donpcevent (st=0x7fffedd6afc4)
    at script.cpp:11115
        event = 0x7fffd7f8aaa4 "dup_5_110033776::OnDisable"
#11 0x00000000005b556d in run_func (st=0x7fffedd6afc4) at script.cpp:3995
        data = <value optimized out>
        i = <value optimized out>
        start_sp = <value optimized out>
        end_sp = <value optimized out>
        func = 20178
#12 0x00000000005b9dc0 in run_script_main (st=0x7fffedd6afc4)
    at script.cpp:4270
        cmdcount = 655313
        gotocount = 2048
        sd = <value optimized out>
        stack = 0x7fffe9f97b0c
#13 0x00000000005442ca in npc_event_sub (sd=0x77f4ff0, ev=0x7fffd93448c4, 
    eventname=0x7fffd781f2f0 "dup_5_110033775::OnMobDead") at npc.cpp:878
No locals.
#14 0x00000000005443ee in npc_event (sd=0x77f4ff0, 
    eventname=0x7fffd781f2f0 "dup_5_110033775::OnMobDead", ontouch=0)
    at npc.cpp:910
        ev = 0x7fffd93448c4
        nd = 0x7fffd7acde9c
        __FUNCTION__ = "npc_event"
#15 0x000000000053cbc5 in mob_dead (md=Unhandled dwarf expression opcode 0xf3
) at mob.cpp:3010
        status = <error reading variable status (Unhandled dwarf expression opcode 0xf3)>
        sd = <value optimized out>
        tmpsd = {0x77f4ff0, 0x0 <repeats 29 times>}
        mvp_sd = 0x77f4ff0
        second_sd = <value optimized out>
        third_sd = 0x0
        pt = {{p = 0x7fffda0a6244, id = 0, zeny = 0, base_exp = 0, 
            job_exp = 0}, {p = 0x0, id = 0, zeny = 0, base_exp = 0, 
            job_exp = 0} <repeats 29 times>}
        i = <value optimized out>
        temp = <value optimized out>
        count = 1
        m = <value optimized out>
        dmgbltypes = <value optimized out>
        mvp_damage = 0
        tick = 216337869
        rebirth = false
        homkillonly = <value optimized out>
#16 0x000000000064763b in status_damage (src=0x77f4ff0, target=0x7fffd781d3f4, 
    dhp=Unhandled dwarf expression opcode 0xf3
) at status.cpp:1844
        status = <value optimized out>
        hp = 118862
        sp = 0
        __FUNCTION__ = "status_damage"
#17 0x0000000000496cc6 in battle_damage (src=0x77f4ff0, target=0x7fffd781d3f4, 
    damage=276848, delay=288, skill_lv=Unhandled dwarf expression opcode 0xf3
) at battle.cpp:272
No locals.
#18 0x0000000000496e6e in battle_delay_damage_sub (tid=Unhandled dwarf expression opcode 0xf3
) at battle.cpp:326
        src = 0x77f4ff0
        target = 0x7fffd781d3f4
        dat = 0x74a2b28
#19 0x0000000000690698 in do_timer (tick=Unhandled dwarf expression opcode 0xf3
) at timer.cpp:370
        tid = 2332
        diff = -14
        __FUNCTION__ = "do_timer"
#20 0x0000000000465ebc in main (argc=1, argv=0x7fffffffde28) at core.cpp:367
        next = <value optimized out>
(gdb) 
```

  * Expected Result: Do not crash.
  * How to Reproduce: 
```
1@gol1,85,31,3	script	#walleddaII1	802,{
end;
	
	OnDisable:
		if (checkwall("edda_bio_wall_step_2_" + 'instance_id) == true)
			delwall "edda_bio_wall_step_2_" + 'instance_id;		
		//delwall "Samp_Walled2";
	OnInstanceInit:
		'instance_id = instance_id();
		'map_swat$ = instance_mapname("1@gol1");		
		hideonnpc strnpcinfo(3);
	end;
	OnEnable:
		setwall 'map_swat$,95,31,12, DIR_WEST, false, "edda_bio_wall_step_2_" + 'instance_id;
		hideoffnpc strnpcinfo(3);
		//setwall instance_mapname("1@gol1"),95,31,12,2,0,"Samp_Walled2";
	end;	
}

1@gol1,137,54,3	script	#walleddaIII1	802,{
end;
	
	OnDisable:
		if (checkwall("edda_bio_wall_step_3_" + 'instance_id) == true)
			delwall "edda_bio_wall_step_3_" + 'instance_id;	
		//delwall "Samp_Walled3";
	OnInstanceInit:
		'instance_id = instance_id();
		'map_swat$ = instance_mapname("1@gol1");	
		hideonnpc strnpcinfo(3);
	end;
	OnEnable:
	
		hideoffnpc strnpcinfo(3);
		setwall 'map_swat$,147,54,12, DIR_WEST, false, "edda_bio_wall_step_3_" + 'instance_id;
		//setwall instance_mapname("1@gol1"),147,54,12,2,0,"Samp_Walled3";
	end;	
}
```

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Badarosk0** [comment]
New crash (Heart Hunter War Base 2) instance script:

```

Program received signal SIGSEGV, Segmentation fault.
map_setcell (m=Unhandled dwarf expression opcode 0xf3
) at map.cpp:3312
3312			case CELL_SHOOTABLE:     mapdata->cell[j].shootable = flag;     break;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 mysql-libs-5.1.73-8.el6_8.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 openssl-1.0.1e-57.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
[K(gdb) bt full
#0  map_setcell (m=Unhandled dwarf expression opcode 0xf3
) at map.cpp:3312
        j = 6116
#1  0x0000000000530c54 in map_iwall_remove (wall_name=Unhandled dwarf expression opcode 0xf3
) at map.cpp:3450
        iwall = 0x7fffd75b9dac
        i = 0
        x1 = 116
        y1 = 30
#2  0x00000000005c6737 in buildin_delwall (st=0x7fffedd6b7e4) at script.cpp:14115
        name = <value optimized out>
#3  0x00000000005c346d in run_func (st=0x7fffedd6b7e4) at script.cpp:4022
        data = <value optimized out>
        i = <value optimized out>
        start_sp = <value optimized out>
        end_sp = <value optimized out>
        func = 20892
#4  0x00000000005c84f0 in run_script_main (st=0x7fffedd6b7e4) at script.cpp:4297
        cmdcount = 655071
        gotocount = 2048
        sd = <value optimized out>
        stack = 0x7fffe9f9873c
#5  0x00000000005553f3 in npc_instanceinit (nd=0x7fffd4b9d10c) at npc.cpp:3469
        ev = 0x5924bf4
        evname = "dup_2_110020417::OnInstanceInit\000p\345n\000\000\000\000\000\000\000\000\000\245\003\000\000@.\237\000\000\000\000\000\374\276\265\331\377\177\000\000`n\370\000\000\000\000\000\000\000\000\000)"
#6  0x0000000000529974 in map_foreachinareaV(int (*)(block_list *, typedef __va_list_tag __va_list_tag *), int16, int16, int16, int16, int16, int, typedef __va_list_tag __va_list_tag *, bool) (func=0x513f70 <instance_npcinit(block_list *, typedef __va_list_tag __va_list_tag *)>, m=1065, x0=<value optimized out>, 
    y0=<value optimized out>, x1=<value optimized out>, y1=<value optimized out>, type=128, ap=<value optimized out>, wall_check=false) at map.cpp:804
        bx = <value optimized out>
        by = <value optimized out>
        cx = 0
        cy = 64
        returnCount = 0
        bl = <value optimized out>
        blockcount = <value optimized out>
        i = 82
        ap_copy = void
#7  0x0000000000529b63 in map_foreachinallarea(int (*)(block_list *, typedef __va_list_tag __va_list_tag *), int16, int16, int16, int16, int16, int, ...) (func=Unhandled dwarf expression opcode 0xf3
)
    at map.cpp:820
        returnCount = 0
        ap = void
#8  0x0000000000514473 in instance_addnpc (im=0x9f2e40) at instance.cpp:358
        mapdata = <value optimized out>
        i = 0
#9  0x0000000000514687 in instance_addmap (instance_id=2) at instance.cpp:527
        i = <value optimized out>
        m = <value optimized out>
        im = 0x9f2e40
        db = 0x7fffeaf96744
        entry = <value optimized out>
#10 0x00000000005147cd in instance_addmap (tid=Unhandled dwarf expression opcode 0xf3
) at instance.cpp:115
No locals.
#11 instance_subscription_timer (tid=Unhandled dwarf expression opcode 0xf3
) at instance.cpp:119
        i = <value optimized out>
        ret = <value optimized out>
        instance_id = 2
        sd = 0x0
        pd = 0x0
        gd = 0x0
        cd = 0x0
        mode = <value optimized out>
#12 0x0000000000514bf7 in instance_create (owner_id=51064, name=0x7fffde561c29 "Heart Hunter War Base 2", mode=IM_PARTY) at instance.cpp:456
        db = <value optimized out>
        sd = 0x0
        pd = 0x7fffd63b2964
        gd = 0x0
        cd = 0x0
        i = 2
        __FUNCTION__ = "instance_create"
#13 0x00000000005de3d1 in buildin_instance_create (st=0x7fffedd6bd04) at script.cpp:21210
        mode = <value optimized out>
        owner_id = 51064
        __FUNCTION__ = "buildin_instance_create"
#14 0x00000000005c346d in run_func (st=0x7fffedd6bd04) at script.cpp:4022
        data = <value optimized out>
        i = <value optimized out>
        start_sp = <value optimized out>
        end_sp = <value optimized out>
        func = 20945
#15 0x00000000005c84f0 in run_script_main (st=0x7fffedd6bd04) at script.cpp:4297
        cmdcount = 655339
        gotocount = 2045
        sd = <value optimized out>
        stack = 0x7fffe9f963ec
#16 0x000000000054db29 in npc_scriptcont (sd=0x7c0b170, id=110020088, closing=false) at npc.cpp:1428
        target = 0x7fffde168984
        __FUNCTION__ = "npc_scriptcont"
#17 0x00000000004cb5a8 in clif_parse (fd=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:21779
        cmd = 184
        packet_len = 7
        sd = 0x7c0b170
        pnum = 0
#18 0x00000000006885dd in do_sockets (next=Unhandled dwarf expression opcode 0xf3
) at socket.cpp:1408
        rfd = {fds_bits = {4194304, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 10792}
        ret = 0
        i = 22
#19 0x000000000046dda5 in main (argc=1, argv=0x7fffffffde28) at core.cpp:369
        next = <value optimized out>
```
@Atemo

**Comment by Badarosk0** [comment]
This problem occurs when the sample code published by @Atemo  in PR happens.
```
	if (checkwall("swat_1_wall_step_1_" + 'instance_id) == true)
		delwall "swat_1_wall_step_1_" + 'instance_id;
	if (checkwall("swat_1_wall_step_2_" + 'instance_id) == true)
		delwall "swat_1_wall_step_2_" + 'instance_id;
	if (checkwall("swat_1_wall_step_3_" + 'instance_id) == true)
		delwall "swat_1_wall_step_3_" + 'instance_id;
	setwall 'map_swat$,116,30, 36, DIR_NORTH, false, "swat_1_wall_step_1_" + 'instance_id;
	setwall 'map_swat$,151,30, 30, DIR_NORTH, false, "swat_1_wall_step_2_" + 'instance_id;
	setwall 'map_swat$,250,30, 16, DIR_NORTH, false, "swat_1_wall_step_3_" + 'instance_id;
	end;
```
Is there a problem with delwall inside instance.

I tried using it on a custom instance I was creating and needed to remove the command. Always crash the map-server.
@aleos89

**Comment by attackjom** [comment]
This bug is deadly  it make myserver crash 2-3 times per day

and finally I decide to remove the trouble-instance from my server.
