### ISSUE TITLE
Crash Server When create instance

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#4057]
* **rAthena Hash**: 

06c8e0b49

* **Client Date**: 
20180621

* **Server Mode**: 
RE

* **Description of Issue**: 
  * Result: When someone try to create Instance make map server crash
  * Expected Result: Should no
  * How to Reproduce: Create Instance

  * Official Information:
  

* **Modifications that may affect results**: 
  
  

This Is the gdb result :
Program received signal SIGSEGV, Segmentation fault.
instance_create (owner_id=owner_id@entry=1451, name=0x7fffe3bee6ef "Sky Fortress Invasion",
    mode=mode@entry=IM_PARTY) at instance.cpp:425
425             instance_data[i].type = db->id;
(gdb) bt full
#0  instance_create (owner_id=owner_id@entry=1451, name=0x7fffe3bee6ef "Sky Fortress Invasion",
    mode=mode@entry=IM_PARTY) at instance.cpp:425
        db = 0x0
        sd = 0x0
        pd = 0x7fffeca0d5ec
        gd = 0x0
        cd = 0x0
        i = 1
        __FUNCTION__ = "instance_create"
#1  0x00005555556d642d in buildin_instance_create (st=0x7ffff0b52f54) at script.cpp:19769
        mode = <optimized out>
        owner_id = 1451
        __FUNCTION__ = "buildin_instance_create"
#2  0x00005555556bd824 in run_func (st=st@entry=0x7ffff0b52f54) at script.cpp:4016
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        end_sp = <optimized out>
        func = 519
#3  0x00005555556c27e8 in run_script_main (st=0x7ffff0b52f54) at script.cpp:4291
        c = C_FUNC
        cmdcount = 655322
        gotocount = 2047
        sd = <optimized out>
        stack = 0x7fffecade8dc
#4  0x000055555564f23d in npc_scriptcont(map_session_data*, int, bool) ()
    at /usr/include/c++/8/ext/new_allocator.h:116
No symbol table info available.
#5  0x00005555555d5385 in clif_parse (fd=20) at clif.cpp:21039
        cmd = <optimized out>
        packet_len = 7
        sd = <optimized out>
        pnum = 0
        cmd = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
        packet_len = <optimized out>
        sd = <optimized out>
        pnum = <optimized out>
#6  clif_parse (fd=20) at clif.cpp:20906
        cmd = <optimized out>
        packet_len = <optimized out>
        sd = <optimized out>
#7  0x0000555555578545 in main () at /usr/include/c++/8/bits/shared_ptr_base.h:1147
No symbol table info available.

**Comment by cahya1992** [comment]
Already solved just Human error :(
