### ISSUE TITLE
Map Server Crash - skill_delunit

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#4119]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ce1508a01c68dee80544242b470987742f3b3ece

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Map server crash
  * Expected Result: No crash

gdb:
```
skill_delunit (unit=0x7fffe078f534) at skill.cpp:18033
18033           if( group->state.song_dance&0x1 ) //Cancel dissonance effect.
```
bt full
```
skill_delunit (unit=0x7fffe078f534) at skill.cpp:18033
18033           if( group->state.song_dance&0x1 ) //Cancel dissonance effect.

#0  skill_delunit (unit=0x7fffe078f534) at skill.cpp:18033
        group = 0xfdfdfdfdfdfdfdfd
        unit = 0x7fffe078f534
#1  0x00000000005e40f7 in skill_timerskill (tid=<optimized out>,
    tick=52932766, id=<optimized out>, data=<optimized out>) at skill.cpp:4186
        src = 0x7fffdedee51c
        target = 0x9ec6b70
        ud = 0x7fffdedee53c
        skl = 0x7fffee01eb44
        unit = 0x7fffe078f534
        range = <optimized out>
        __FUNCTION__ = "skill_timerskill"
#2  0x000000000040b494 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 682
        diff = -17
#3  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:368
```

**Comment by Lemongrass3110** [comment]
Duplicate of #3112
