### ISSUE TITLE
Map-server Crash (delwaitingroom script)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4173]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Map server crash:
```
[Error]: WFIFOSET: Maximum write buffer size for client connection 34 exceeded, most likely caused by packet 0x00d8 (len=6, ip=170.244.236.59).
terminate called after throwing an instance of 'std::invalid_argument'
Program received signal SIGABRT, Aborted.
0x00007ffff5a49495 in raise () from /lib64/libc.so.6
(gdb) 
(gdb) 
(gdb) bt full
#0  0x00007ffff5a49495 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff5a4ac75 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff6303a8d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff6301be6 in ?? () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff6301c13 in std::terminate() () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff6301d32 in __cxa_throw () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#6  0x0000000000688c1e in WFIFOSET (fd=34, len=6) at socket.cpp:1237
        newreserve = <value optimized out>
        s = 0x7ffff4663ecc
#7  0x00000000004c81a5 in clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *) (bl=0x77403c0, ap=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:399
        buf = 0x7fffffffdb50 "\330"
        len = 6
        type = <value optimized out>
        fd = 34
        src_bl = 0x7fffddb9b504
        ap = <error reading variable ap (Unhandled dwarf expression opcode 0xf3)>
        bl = 0x77403c0
        sd = 0x77403c0
#8  0x0000000000529ad4 in map_foreachinareaV(int (*)(block_list *, typedef __va_list_tag __va_list_tag *), int16, int16, int16, int16, int16, int, typedef __va_list_tag __va_list_tag *, bool) (func=0x4c8030 <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)>, m=171, x0=<value optimized out>, 
    y0=<value optimized out>, x1=<value optimized out>, y1=<value optimized out>, type=1, ap=<value optimized out>, wall_check=false) at map.cpp:804
        bx = <value optimized out>
        by = <value optimized out>
        cx = 32767
        cy = 49
        returnCount = 0
        bl = <value optimized out>
        blockcount = <value optimized out>
        i = 0
        ap_copy = void
#9  0x0000000000529cc3 in map_foreachinallarea(int (*)(block_list *, typedef __va_list_tag __va_list_tag *), int16, int16, int16, int16, int16, int, ...) (func=Unhandled dwarf expression opcode 0xf3
)
    at map.cpp:820
        returnCount = 0
        ap = void
#10 0x00000000004c8c5f in clif_send (buf=0x7fffffffdb50 "\330", len=6, bl=0x7fffddb9b504, type=AREA_WOSC) at clif.cpp:462
        i = <value optimized out>
        sd = <value optimized out>
        tsd = <value optimized out>
        p = 0x0
        g = 0x0
        bg = 0x0
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = <value optimized out>
        iter = <value optimized out>
        __FUNCTION__ = "clif_send"
#11 0x00000000004d03bb in clif_clearchat (cd=0x7fffdc02c41c, fd=0) at clif.cpp:4211
        buf = "\330\000I\265\a\000\000\000\373\270h\000\000\000\000\000\000\270h\000\000\000\000\000l\356[\334\377\177\000"
        __FUNCTION__ = "clif_clearchat"
#12 0x00000000004be8e5 in chat_deletenpcchat (nd=0x7fffddb9b504) at chat.cpp:443
        cd = 0x7fffdc02c41c
        __FUNCTION__ = "chat_deletenpcchat"
#13 0x00000000005c62dc in buildin_delwaitingroom (st=Unhandled dwarf expression opcode 0xf3
) at script.cpp:12567
        nd = <value optimized out>
#14 0x00000000005c37ad in run_func (st=0x7fffedd6ad84) at script.cpp:4022
        data = <value optimized out>
        i = <value optimized out>
        start_sp = <value optimized out>
        end_sp = <value optimized out>
        func = 12528
#15 0x00000000005c8830 in run_script_main (st=0x7fffedd6ad84) at script.cpp:4297
        cmdcount = 655358
        gotocount = 2048
        sd = <value optimized out>
        stack = 0x7fffe9ff1b54
#16 0x000000000054b419 in npc_timerevent (tid=4957, tick=3781171514, id=110019857, data=104162904) at npc.cpp:653
        old_rid = 0
        old_timer = 0
        old_tick = 3781170514
        nd = 0x7fffddb9b504
        te = 0x7fffddebb8e4
        ted = 0x6356658
        sd = 0x0
#17 0x000000000068ce08 in do_timer (tick=Unhandled dwarf expression opcode 0xf3
) at timer.cpp:374
        tid = 4957
        diff = -18
        __FUNCTION__ = "do_timer"
#18 0x000000000046defd in main (argc=1, argv=0x7fffffffde28) at core.cpp:368
        next = <value optimized out>
```

  * Expected Result: 

  * How to Reproduce: 
When using this script it seems that the crash occurs:
```
    OnTimer1000:
    delwaitingroom;
    waitingroom "~ Weapons", 0;
    specialeffect 379;
    end;

    OnTimer1500:
    delwaitingroom;
    waitingroom "~ Cash Quests", 0;
    stopnpctimer;
    setnpctimer 0;
    specialeffect 411;
    startnpctimer;
    end;

    OnInit:
    initnpctimer;
    end;
```

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Normynator** [comment]
Same as in #4174
