### ISSUE TITLE
Map-Server Crash (skilleffect 34,0; )

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4174]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Map server crash: 
```
[Error]: WFIFOSET: Maximum write buffer size for client connection 16 exceeded, most likely caused by packet 0x09cb (len=17, ip=200.159.193.6).
Program received signal SIGABRT, Aborted.
0x00007ffff5a49495 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 mysql-libs-5.1.73-8.el6_8.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 openssl-1.0.1e-57.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
[K(gdb) bt full
#0  0x00007ffff5a49495 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff5a4ac75 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff6303a8d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff6301be6 in ?? () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff6301c13 in std::terminate() () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff6301d32 in __cxa_throw () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#6  0x000000000068837e in WFIFOSET (fd=16, len=17) at socket.cpp:1237
        newreserve = <value optimized out>
        s = 0x7ffff46655ac
#7  0x00000000004c80b5 in clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *) (bl=0x90fe200, ap=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:399
        buf = 0x7fffffffdae0 "\313\t\""
        len = 17
        type = <value optimized out>
        fd = 16
        src_bl = 0x5d6f740
        ap = <error reading variable ap (Unhandled dwarf expression opcode 0xf3)>
        bl = 0x90fe200
        sd = 0x90fe200
#8  0x0000000000529a24 in map_foreachinareaV(int (*)(block_list *, typedef __va_list_tag __va_list_tag *), int16, int16, int16, int16, int16, int, typedef __va_list_tag __va_list_tag *, bool) (func=0x4c7f40 <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)>, m=171, x0=<value optimized out>, 
    y0=<value optimized out>, x1=<value optimized out>, y1=<value optimized out>, type=1, ap=<value optimized out>, wall_check=false) at map.cpp:804
        bx = <value optimized out>
        by = <value optimized out>
        cx = 32767
        cy = 7532528
        returnCount = 0
        bl = <value optimized out>
        blockcount = <value optimized out>
        i = 9
        ap_copy = void
#9  0x0000000000529c13 in map_foreachinallarea(int (*)(block_list *, typedef __va_list_tag __va_list_tag *), int16, int16, int16, int16, int16, int, ...) (func=Unhandled dwarf expression opcode 0xf3
)
    at map.cpp:820
        returnCount = 0
        ap = void
#10 0x00000000004c8b6f in clif_send (buf=0x7fffffffdae0 "\313\t\"", len=17, bl=0x5d6f740, type=AREA) at clif.cpp:462
        i = <value optimized out>
        sd = <value optimized out>
        tsd = <value optimized out>
        p = 0x0
        g = 0x0
        bg = 0x0
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = <value optimized out>
        iter = <value optimized out>
        __FUNCTION__ = "clif_send"
#11 0x00000000004d34a0 in clif_skill_nodamage (src=0x5d6f740, dst=0x5d6f740, skill_id=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:5797
        buf = "\313\t\"\000\000\000\000\000`\342\036\000`\342\036\000\001"
        offset = 2
        success = true
        __FUNCTION__ = "clif_skill_nodamage"
#12 0x00000000005e7cdf in buildin_skilleffect (st=Unhandled dwarf expression opcode 0xf3
) at script.cpp:14913
        sd = 0x5d6f740
        skill_id = 34
        skill_lv = 0
        __FUNCTION__ = "buildin_skilleffect"
#13 0x00000000005c2bfd in run_func (st=0x7fffedd6bfa4) at script.cpp:4022
        data = <value optimized out>
        i = <value optimized out>
        start_sp = <value optimized out>
        end_sp = <value optimized out>
        func = 20669
#14 0x00000000005c7c80 in run_script_main (st=0x7fffedd6bfa4) at script.cpp:4297
        cmdcount = 655304
        gotocount = 2045
        sd = <value optimized out>
        stack = 0x7fffe9f9653c
#15 0x000000000054d8dd in npc_click (sd=0x5d6f740, nd=0x7fffde053bec) at npc.cpp:1344
        __FUNCTION__ = "npc_click"
#16 0x00000000004cb618 in clif_parse (fd=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:21767
        cmd = 144
        packet_len = 7
        sd = 0x5d6f740
        pnum = 0
#17 0x000000000068808d in do_sockets (next=Unhandled dwarf expression opcode 0xf3
) at socket.cpp:1408
        rfd = {fds_bits = {262144, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 19702}
        ret = 0
        i = 18
#18 0x000000000046de55 in main (argc=1, argv=0x7fffffffde28) at core.cpp:369
        next = <value optimized out>
```
  * Expected Result: 
  * How to Reproduce: 
When using the script ```skilleffect 34,0;``` on a Healer NPC this crash may occur.

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Normynator** [comment]
WFIFOSET does not use „throw“ when using the hash you provided.
So you probably have modifications in your code.

**Comment by anacondaq** [comment]
This is not "his" modification in the code. I saw it frequently many times too in clean rAthena, but not really latest revision. This is some kind of changes related to new features with packets which not properly implemented.

**Comment by Normynator** [comment]
It is because I was the one who gave him the modification.
