### ISSUE TITLE
Map-Server Crash

### ISSUE THREAD

**Issue by siriousb** [rathena/rathena#4180]
* **rAthena Hash**: ae69e506263f9b183c945f49b1d88c5fc2b73a6a
* **Client Date**: 20180620
* **Server Mode**: Renewal
* **Crash GDB**: 
```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000055abb7 in run_script_main (st=0x6c2319368a44) at script.cpp:4305
4305                    enum c_op c = get_com(st->script->script_buf,&st->pos);
(gdb) bt full
#0  0x000000000055abb7 in run_script_main (st=0x6c2319368a44) at script.cpp:4305
        c = <optimized out>
        cmdcount = 655348
        gotocount = 2048
        sd = <optimized out>
        stack = 0x6c2314251fcc
#1  0x000000000055b1bd in run_script_timer (tid=<optimized out>, tick=<optimized out>,
    id=<optimized out>, data=<optimized out>) at script.cpp:4172
        st = <optimized out>
        node = 0x6c230690204c
#2  0x0000000000617f3a in do_timer (tick=<optimized out>) at timer.c:369
        tid = 3801
        diff = -19
        __FUNCTION__.4296 = "do_timer"
#3  0x00000000004077ac in main (argc=1, argv=0x74a67d1f7d88) at core.cpp:370
        next = <optimized out>
(gdb)
```

Files:

- script.cpp:4305
- script.cpp:4172
- timer.c:369
- core.cpp:370

**Comment by aleos89** [comment]
Possibly related to #2833. Do you have some kind of daily reward NPC or something? Previous report was unable to find the root of the crash.

**Comment by siriousb** [comment]
I use Attendance to daily reward...

**Comment by Lemongrass3110** [comment]
No further information since May.
