### ISSUE TITLE
Double Casting Crash Map Server in Pre-Re

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4676]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3ddf8c5a6e6b3571699992fee9935633855b5fb0

* **Client Date**: 20180620

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Map server crash when professor using double casting.
  * Result: Map server crash after professor using double casting and cast fire bolt/cold bolt at ant egg or any target players.
  * Expected Result: Shouldnt crash the map server
  * How to Reproduce: @job as professor, @allskill and use double casting + fire bolt at any target. Ive tried to ant egg.

**Comment by reunite-ro** [comment]
I leave the gdb log here

```
#0  0x00000000005c764f in skill_attack (attack_type=attack_type@entry=2,
    src=src@entry=0x4a25c30, dsrc=<optimized out>, dsrc@entry=0x4a25c30,
    bl=bl@entry=0x7fffddaef8a4, skill_id=skill_id@entry=19,
    skill_lv=skill_lv@entry=10, tick=tick@entry=77924073, flag=flag@entry=0)
    at skill.cpp:3766
        sstatus = <optimized out>
        sc = 0x4a261e0
        tsc = 0x0
        damage = 30
        additional_effects = true
        dmg = {damage = 30, damage2 = 0, type = <incomplete type>, div_ = 10,
          amotion = 471, dmotion = 721, blewcount = 0, flag = <optimized out>,
          miscflag = <optimized out>, dmg_lv = <optimized out>,
          isspdamage = <optimized out>}
        tstatus = 0x7fffddaefd90
        sd = 0x4a25c30
        tsd = <optimized out>
        type = <optimized out>
        shadow_flag = <optimized out>
        __FUNCTION__ = "skill_attack"
        rmdamage = 0 '\000'
        dmg_type = <incomplete type>
#1  0x00000000005c16e6 in skill_castend_damage_id (src=src@entry=0x4a25c30,
---Type <return> to continue, or q <return> to quit---
    bl=bl@entry=0x7fffddaef8a4, skill_id=19, skill_lv=10,
    tick=tick@entry=77924073, flag=flag@entry=0) at skill.cpp:5341
        sc = 0x4a261e0
        __FUNCTION__ = "skill_castend_damage_id"
        sd = 0x4a25c30
        tstatus = 0x7fffddaefd90
        tsc = 0x0
#2  0x00000000005ea31b in skill_castend_id (tid=<optimized out>,
    tick=<optimized out>, id=<optimized out>, data=<optimized out>)
    at skill.cpp:11493
        fail = false
        res = -1 '\377'
        sc = <optimized out>
        flag = 0
        target = 0x7fffddaef8a4
        src = 0x4a25c30
        sd = <optimized out>
        md = <optimized out>
        ud = 0x4a25c50
#3  0x000000000063f442 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 53
        diff = <optimized out>
        do_timer(long)::__FUNCTION__ = "do_timer"
---Type <return> to continue, or q <return> to quit---
#4  0x0000000000407db5 in main (argc=1, argv=0x7fffffffe628) at core.cpp:368
        next = <optimized out>
```

**Comment by reunite-ro** [comment]
From all the latest commits that I see in rAthena, I think https://github.com/rathena/rathena/commit/836eda487955f308c812556f92df83987ff44743 this commit create the map crash issue.
