### ISSUE TITLE
SC_Dancing Debug

### ISSUE THREAD

**Issue by ArtixPH** [rathena/rathena#4766]
* **rAthena Hash**: 
e60dc3a81

* **Client Date**: 
2018-06-21aRagexe

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
![image](https://user-images.githubusercontent.com/53513143/78420320-8e173b00-7680-11ea-823e-a0c41051bd63.png)

* **GDB Result**: 
```#0  0x0000556811970123 in std::advance<std::__detail::_Node_iterator<std::pair<unsigned short const, std::shared_ptr<s_skill_abra_db> >, false, false>, unsigned long> (__n=<optimized out>, __i=<synthetic pointer>...)
    at /usr/include/c++/5/bits/stl_iterator_base_funcs.h:176
        __d = <optimized out>
        __d = <optimized out>
#1  skill_castend_nodamage_id (src=0x556817743320, bl=0x556817743320, skill_id=<optimized out>, skill_lv=10, tick=679587567, flag=0) at skill.cpp:6422
        abra_skill_lv = <optimized out>
        checked = 2
        abra_skill_id = <optimized out>
        checked_max = 462
        abra_spell = {<std::__detail::_Node_iterator_base<std::pair<unsigned short const, std::shared_ptr<s_skill_abra_db> >, false>> = {_M_cur = 0x0}, <No data fields>}
        sd = <optimized out>
        dstsd = <optimized out>
        md = <optimized out>
        dstmd = 0x0
        hd = <optimized out>
        mer = 0x0
        sstatus = 0x556817743874
        tstatus = 0x556817743874
        tsc = 0x7ffc61d5dd76
        tsce = <optimized out>
        i = <optimized out>
        type = <optimized out>
        __FUNCTION__ = "skill_castend_nodamage_id"
#2  0x00005568119774db in skill_castend_id (tid=<optimized out>, tick=tick@entry=679587567, id=<optimized out>, data=data@entry=0) at skill.cpp:11478
        fail = false
        res = <optimized out>
        target = 0x556817743320
        src = 0x556817743320
        sd = <optimized out>
        md = 0x0
        ud = 0x556817743340
        sc = <optimized out>
        flag = 0
#3  0x00005568119b763e in unit_skilluse_id2 (src=0x556817743320, target_id=2001460, skill_id=<optimized out>, skill_lv=<optimized out>, casttime=0, castcancel=<optimized out>) at unit.cpp:1933
        ud = 0x556817743340
        tstatus = 0x556817743874
        sc = <optimized out>
        sd = 0x556817743320
        target = <optimized out>
        tick = 679587567
        combo = 0
        range = <optimized out>
        inf = 116 't'
        inf2 = 393491232
        __FUNCTION__ = "unit_skilluse_id2"
#4  0x00005568117fc285 in clif_parse (fd=<optimized out>) at clif.cpp:21077
        cmd = <optimized out>
        packet_len = 10
        sd = <optimized out>
        pnum = 0
#5  0x00005568117a07ed in do_sockets (next=<optimized out>) at socket.cpp:1407
        ret = <optimized out>
        i = 83
        ret = <optimized out>
        i = <optimized out>
        it = <optimized out>
        fd = <optimized out>
        sock = <optimized out>
#6  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:369
        next = <optimized out>
```

* **Modifications that may affect results**: 
No Modifications except Gepard.

**Comment by aleos89** [comment]
Duplicate of #1986. Just another interaction of messy song code (In pre-renewal only now).
