### ISSUE TITLE
Map Server Crash

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5207]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ff38cf70d2e6c73523f5809cbdc8fc8f71292383

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000052ec23 in party_foreachsamemap (
    func=func@entry=0x5d36d0 <skill_area_sub(block_list*, __va_list_tag*)>, 
    sd=sd@entry=0xaf33f20, range=14) at party.cpp:1384
1384			if(psd->bl.m!=sd->bl.m || !psd->bl.prev)
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-24.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 openssl-1.0.1e-58.el6_10.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
(gdb) bt full
#0  0x000000000052ec23 in party_foreachsamemap (
    func=func@entry=0x5d36d0 <skill_area_sub(block_list*, __va_list_tag*)>, 
    sd=sd@entry=0xaf33f20, range=14) at party.cpp:1384
        psd = 0x41
        p = <optimized out>
        i = <optimized out>
        x0 = 151
        y0 = 113
        x1 = 179
        y1 = 141
        blockcount = 1
        total = 0
        bg = std::shared_ptr (count 3, weak 0) 0x63d70f0
        __FUNCTION__ = "party_foreachsamemap"
        bg_mode = <optimized out>
        max_i = <optimized out>
        list = {0xaf33f20, 0x480204
     <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)+372>, 
          0x0, 0x0, 0x1, 0x7fffffffd618, 
          0x480090 <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)>, 0xf, 0x0, 0x4f065a
     <map_foreachinareaV(int (*)(block_list*, __va_list_tag*), short, short, short, short, short, int, __va_list_tag*, bool)+922>, 0x4b0000002f, 0xb}
#1  0x000000000060db1b in skill_castend_nodamage_id (src=0xaf33f20, 
    bl=0xaf33f20, skill_id=<optimized out>, skill_lv=10, tick=6947560606, 
    flag=0) at skill.cpp:7686
        sd = <optimized out>
        dstsd = <optimized out>
        md = <optimized out>
        dstmd = 0x0
        hd = <optimized out>
        mer = 0x0
        sstatus = <optimized out>
        tstatus = <optimized out>
        tsc = <optimized out>
        tsce = <optimized out>
        i = <optimized out>
        type = <optimized out>
        __FUNCTION__ = "skill_castend_nodamage_id"
#2  0x00000000006247d6 in skill_castend_id (tid=<optimized out>, 
    tick=6947560606, id=<optimized out>, data=<optimized out>)
    at skill.cpp:12169
        fail = false
        res = <optimized out>
        target = <optimized out>
        src = 0xaf33f20
        sd = <optimized out>
        md = <optimized out>
        ud = <optimized out>
        sc = <optimized out>
        flag = <optimized out>
#3  0x000000000040cb58 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 3394
        diff = -11
#4  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:380
No locals.
(gdb) 
```
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Looks like your party data got corrupted.
One of your player sessions is pointing to 0x41, which is pretty unrealistic.

Do you have any modifications?

**Comment by Badarosk0** [comment]
> Looks like your party data got corrupted.
> One of your player sessions is pointing to 0x41, which is pretty unrealistic.
> 
> Do you have any modifications?

Yes, in this case it was a modification. I will close this issue at the moment. Thank you.
