### ISSUE TITLE
Map Server Crash 

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5337]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/dbe5ba748bf0c50d09cda98ad4f968e0cf1a2905

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: For some reason this crash map occurred. I have not yet identified how to generate this crash.
```
Info]: [Instance] Created: Last room (256)
[Info]: [Instance] Destroyed: Last room (253)

Program received signal SIGSEGV, Segmentation fault.
0x00000000004e4015 in map_delblock (bl=bl@entry=0x7fffdef533bc) at map.cpp:450
450				mapdata->block[pos] = bl->next;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-24.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 openssl-1.0.1e-58.el6_10.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
[K(gdb) bt full
#0  0x00000000004e4015 in map_delblock (bl=bl@entry=0x7fffdef533bc)
    at map.cpp:450
        pos = <optimized out>
        bl = 0x7fffdef533bc
#1  0x0000000000668bd6 in unit_remove_map_ (bl=bl@entry=0x7fffdef533bc, 
    clrtype=<optimized out>, file=file@entry=0x7107e3 "unit.cpp", 
    line=line@entry=1310, 
    func=func@entry=0x710c78 <unit_warp(block_list*, short, short, short, clr_type)::__FUNCTION__> "unit_warp") at unit.cpp:3196
        ud = <optimized out>
        sc = 0x7fffdef53994
        __FUNCTION__ = "unit_remove_map_"
#2  0x0000000000669769 in unit_warp (bl=bl@entry=0x7fffdef533bc, m=896, 
    x=<optimized out>, y=<optimized out>, type=type@entry=CLR_TELEPORT)
    at unit.cpp:1310
        ud = 0x7fffdef533dc
        __FUNCTION__ = "unit_warp"
#3  0x0000000000669b72 in unit_teleport_timer (tid=<optimized out>, 
    tick=<optimized out>, id=<optimized out>, data=14) at unit.cpp:199
        bl = 0x7fffdef533bc
#4  0x000000000040ce28 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 84846
        diff = -9
---Type <return> to continue, or q <return> to quit---
#5  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:380
No locals.
(gdb) 
```
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Looks to be similar to #4363.
