### ISSUE TITLE
crash in clif_efst_status_change_sub

### ISSUE THREAD

**Issue by samers1** [rathena/rathena#5568]
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/preragnarok/map-server_pre...done.
[New LWP 38990]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server_pre'.
Program terminated with signal 11, Segmentation fault.
#0  clif_efst_status_change_sub (tbl=0x4710bb0, bl=0x4710bb0, target=AREA)
    at clif.cpp:6292
6292                    enum sc_type type = sc_display[i]->type;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64 ke                                                                                                                                                             yutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-                                                                                                                                                             19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-                                                                                                                                                             4.8.5-44.el7.x86_64 mariadb-libs-5.5.68-1.el7.x86_64 openssl-libs-1.0.2k-19.el7.                                                                                                                                                             x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt full
#0  clif_efst_status_change_sub (tbl=0x4710bb0, bl=0x4710bb0, target=AREA)
    at clif.cpp:6292
        type = <optimized out>
        sc = <optimized out>
        td = <optimized out>
        tick_total = <optimized out>
        cur_tick = <optimized out>
        td_total = <optimized out>
        tick = <optimized out>
        i = <optimized out>
        sc_display = <optimized out>
        sc_display_count = <optimized out>
        spheres_sent = true
        bl = 0x4710bb0
        tbl = 0x4710bb0
#1  0x00000000004abffa in clif_spawn (bl=bl@entry=0x4710bb0,
    walking=walking@entry=false) at clif.cpp:1654
        sd = 0x4710bb0
        vd = 0x47110b0
#2  0x00000000004af70a in clif_parse_LoadEndAck (fd=<optimized out>,
    sd=0x4710bb0) at clif.cpp:10673
        guild_notice = false
        mapdata = 0xa5a220 <map+614656>
---Type <return> to continue, or q <return> to quit---
#3  0x0000000000477bf5 in clif_parse (fd=13) at clif.cpp:22318
        cmd = <optimized out>
        packet_len = 2
        sd = 0x4710bb0
        pnum = 0
#4  0x000000000040bf25 in do_sockets (next=<optimized out>) at socket.cpp:1411
        rfd = {fds_bits = {8192, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 18995}
        ret = <optimized out>
        i = 13
#5  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:381
No locals.
```

**Comment by samers1** [comment]
i put that correction:
https://github.com/rathena/rathena/pull/5280
And not works.

**Comment by Lemongrass3110** [comment]
Please follow the issue template and provide the necessary information.

**Comment by samers1** [comment]
@Lemongrass3110 

rAthena Hash: 

e073870

Client Date: 
#define PACKETVER 20180620

Server Mode: 

Pre-renewal

I dont make manys modification on src.
