### ISSUE TITLE
Map Crash on feeding any pet

### ISSUE THREAD

**Issue by mikkotandoc** [rathena/rathena#5885]
I am crashing on the latest code of the rAthena. Tried gdb it is not producing errors and map server is freezing. The scenario is feeding pets (poring, poporing, etc).

```
GDB LOG :    from /usr/lib64/mysql/libmysqlclient.so.18
(gdb) No symbol table info available.
(gdb) #1  0x00007ffff7090df0 in vio_read ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
(gdb) #2  0x00007ffff7090e71 in vio_read_buff ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
(gdb) #3  0x00007ffff7074fba in my_real_read(st_net*, unsigned long*) ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
(gdb) #4  0x00007ffff7075e2c in my_net_read ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
(gdb) #5  0x00007ffff706884c in cli_safe_read ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
(gdb) #6  0x00007ffff7069ebb in cli_read_query_result ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
(gdb) #7  0x00007ffff706b0f6 in mysql_real_query ()
(gdb)    from /usr/lib64/mysql/libmysqlclient.so.18
Undefined command: "from".  Try "help".
(gdb) No symbol table info available.
```

**Comment by aleos89** [comment]
Please follow the bug report template next time you submit a bug.

Are you sure your freeze is not related to this 3d8570062847092fd28f334505d239503b2113ba?

**Comment by mikkotandoc** [comment]
I solved it by removing pet feeding logs. Whenever I try to enable pet feeding logs it is crashing when player feeds pet.
