### ISSUE TITLE
Unit warp make server crash

### ISSUE THREAD

**Issue by sinju92** [rathena/rathena#5921]
* **rAthena Hash**: 

26632604f

* **Client Date**: 201809019

* **Server Mode**: Pre renewal

* **Description of Issue**: 
```
#0  0x000055555565a88e in map_delblock (bl=bl@entry=0x7fffedd58adc) at map.cpp:398
        pos = <optimized out>
        mapdata = <optimized out>
#1  0x00005555557f3586 in unit_remove_map_ (bl=bl@entry=0x7fffedd58adc, clrtype=<optimized out>,
    file=file@entry=0x555555876102 "unit.cpp", line=line@entry=1311,
    func=func@entry=0x5555558763e8 <unit_warp(block_list*, short, short, short, clr_type)::__FUNCTION__> "unit_warp") at unit.cpp:3247
        ud = <optimized out>
        sc = 0x7fffedd59094
#2  0x00005555557f3f42 in unit_warp (bl=bl@entry=0x7fffedd58adc, m=724, x=<optimized out>,
    y=<optimized out>, type=type@entry=CLR_TELEPORT) at unit.cpp:1311
        ud = 0x7fffedd58afc
        __FUNCTION__ = "unit_warp"
#3  0x00005555557f4222 in unit_teleport_timer (tid=<optimized out>, tick=<optimized out>,
    id=<optimized out>, data=14) at unit.cpp:202
        msd = <optimized out>
        bl = 0x7fffedd58adc
        mast_tid = <optimized out>
#4  0x000055555557bcc8 in main ()
No symbol table info available.
```
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: Gepard

**Comment by aleos89** [comment]
Do you have any ways of reproducing this error? Looks like someone teleported and then immediately logged off or something else of that nature.

**Comment by Lemongrass3110** [comment]
No input for 1 1/2 years.
