### ISSUE TITLE
pc_baselevelchanged map crash

### ISSUE THREAD

**Issue by mrboob** [rathena/rathena#6229]
* **rAthena Hash**:  fe7cb5a33f4a8588f025fbd7f383feeea4b5ab19

* **Client Date**:  2018-06-21aRagexeRE

* **Server Mode**:  Pre-Renewal

* **Description of Issue**: 
  * Result:  

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555556d125c in pc_baselevelchanged (sd=sd@entry=0x55555c565fc0) at pc.cpp:7395
7395                            if( sd->inventory_data[ sd->equip_index[i] ]->elvmax && sd->status.base_level > (unsigned int)sd->inventory_data[ sd->equip_index[i] ]->elvmax )
(gdb) bt full
#0  0x00005555556d125c in pc_baselevelchanged (sd=sd@entry=0x55555c565fc0) at pc.cpp:7395
        i = <optimized out>
#1  0x00005555556d1521 in pc_checkbaselevelup (sd=sd@entry=0x55555c565fc0) at pc.cpp:7383
        next = <optimized out>
        base_level = <optimized out>
#2  0x00005555556d1a9d in pc_gainexp (sd=sd@entry=0x55555c565fc0, src=src@entry=0x7fffbbdc074c,
    base_exp=47581666, job_exp=<optimized out>, exp_flag=exp_flag@entry=0 '\000') at pc.cpp:7599
        nextb = 471547761
        nextj = 999999999
        flag = <optimized out>
#3  0x000055555568a54a in mob_dead (md=md@entry=0x7fffbbdc074c, src=src@entry=0x55555c565fc0,
    type=type@entry=0) at mob.cpp:2720
        flag = 1
        zeny = 0
        job_exp = <optimized out>
        per = <optimized out>
        base_exp = <optimized out>
        bonus = 100
        pnum = 0
        status = 0x7fffbbdc1680
        sd = <optimized out>
        tmpsd = {0x55555c565fc0, 0x0 <repeats 29 times>}
        mvp_sd = 0x55555c565fc0
        second_sd = 0x55555c565fc0
        third_sd = 0x0
        pt = {{p = 0x0, id = 0, zeny = 0, base_exp = 0, job_exp = 0} <repeats 30 times>}
        i = 0
        temp = <optimized out>
        count = 1
        m = 220
        dmgbltypes = <optimized out>
        mvp_damage = <optimized out>
        tick = 45278738005
        rebirth = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        homkillonly = <optimized out>
        merckillonly = false
        isMvp = true
#4  0x00005555557dd75e in status_damage (src=src@entry=0x55555c565fc0,
    target=target@entry=0x7fffbbdc074c, dhp=dhp@entry=764506, dsp=dsp@entry=0,
    walkdelay=walkdelay@entry=480, flag=flag@entry=0, skill_id=271) at status.cpp:2430
        status = <optimized out>
        sc = <optimized out>
        hp = <optimized out>
        sp = 0
        __FUNCTION__ = "status_damage"
#5  0x00005555555bee04 in battle_damage (src=src@entry=0x55555c565fc0,
    target=target@entry=0x7fffbbdc074c, damage=764506, delay=480, skill_lv=<optimized out>,
    skill_id=<optimized out>, dmg_lv=ATK_DEF, attack_type=273, additional_effects=true,
    tick=45278737990, isspdamage=false) at battle.cpp:273
No locals.
#6  0x00005555555bf040 in battle_delay_damage_sub (tid=<optimized out>, tick=45278737990,
    id=<optimized out>, data=93825063743064) at battle.cpp:324
```
  * Expected Result: -
  * How to Reproduce:  -
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by Lemongrass3110** [comment]
We can fix this crash with an additional safeguard, but I think this will not solve your original problem caused by some kind of modification you have in your server.
