### ISSUE TITLE
Map-Server: Program received signal SIGSEGV

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6324]
* **rAthena Hash**: d04e03e

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: Map-Server: Program received signal SIGSEGV
  * Result: 

**Map Server Window**
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000063c9d1 in skill_onskillusage (sd=sd@entry=0xb9ad0a0, bl=<optimized out>,
    skill_id=skill_id@entry=357, tick=<optimized out>) at skill.cpp:2333
2333                            if (rnd()%1000 >= it->rate)
Missing separate debuginfos, use: debuginfo-install MariaDB-shared-10.2.36-1.el7.centos.x86_64 glibc-2.17-317.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb)
```
**GDB BT FULL**
```
(gdb) bt full
#0  0x000000000063c9d1 in skill_onskillusage (sd=sd@entry=0xb9ad0a0, bl=<optimized out>,
    skill_id=skill_id@entry=357, tick=<optimized out>) at skill.cpp:2333
        tbl = <optimized out>
#1  0x000000000063d564 in skill_castend_nodamage_id (src=<optimized out>, bl=<optimized out>,
    skill_id=<optimized out>, skill_lv=<optimized out>, tick=<optimized out>, flag=<optimized out>)
    at skill.cpp:11505
        sd = <optimized out>
        dstsd = <optimized out>
        md = <optimized out>
        dstmd = <optimized out>
        hd = <optimized out>
        mer = <optimized out>
        sstatus = <optimized out>
        tstatus = <optimized out>
        tsc = <optimized out>
        tsce = <optimized out>
        i = <optimized out>
        type = <optimized out>
        __FUNCTION__ = "skill_castend_nodamage_id"
#2  0x0000000000657423 in skill_castend_id (tid=<optimized out>, tick=tick@entry=7493187336,
    id=<optimized out>, data=data@entry=0) at skill.cpp:11872
        fail = false
        res = <optimized out>
        target = <optimized out>
        src = 0xb9ad0a0
        sd = <optimized out>
        md = <optimized out>
        ud = <optimized out>
        sc = <optimized out>
        flag = <optimized out>
#3  0x00000000006abbaf in unit_skilluse_id2 (src=0xb9ad0a0, target_id=2004485,
    skill_id=<optimized out>, skill_lv=<optimized out>, casttime=0, castcancel=<optimized out>)
    at unit.cpp:2040
        ud = <optimized out>
---Type <return> to continue, or q <return> to quit---
        tstatus = 0xb9ad580
        sc = <optimized out>
        sd = 0xb9ad0a0
        target = 0xb9ad0a0
        tick = <optimized out>
        combo = 0
        range = <optimized out>
        __FUNCTION__ = "unit_skilluse_id2"
        inf = <optimized out>
        skill = <optimized out>
#4  0x000000000048178b in clif_parse (fd=28) at clif.cpp:22117
        cmd = <optimized out>
        packet_len = 10
        sd = 0xb9ad0a0
        pnum = 0
        cmd2 = -521242720
#5  0x0000000000412475 in do_sockets (next=<optimized out>) at socket.cpp:1024
        rfd = {fds_bits = {268435456, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 18292}
        ret = <optimized out>
        i = 28
#6  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:381
No locals.
(gdb)
```

  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by vstumpf** [comment]
This crashed in autobonus code, do you have any autobonuses on your character? Which ones?

**Comment by mazvi** [comment]
i got again on rAthena Hash: 487c278

Map Server Screen
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000063dd49 in skill_onskillusage (sd=sd@entry=0x8ac09d0, bl=<optimized out>,
    skill_id=skill_id@entry=357, tick=<optimized out>) at skill.cpp:2336
2336                            if (rnd()%1000 >= it->rate)
(gdb)
```

GDB BT FULL
```
(gdb) BT FULL
#0  0x000000000063dd49 in skill_onskillusage (sd=sd@entry=0x8ac09d0, bl=<optimized out>,
    skill_id=skill_id@entry=357, tick=<optimized out>) at skill.cpp:2336
No locals.
#1  0x000000000063e8c4 in skill_castend_nodamage_id (src=<optimized out>, bl=<optimized out>,
    skill_id=<optimized out>, skill_lv=<optimized out>, tick=<optimized out>, flag=<optimized out>)
    at skill.cpp:11512
        sd = <optimized out>
        dstsd = <optimized out>
        md = <optimized out>
        dstmd = <optimized out>
        hd = <optimized out>
        mer = <optimized out>
        sstatus = <optimized out>
        tstatus = <optimized out>
        tsc = <optimized out>
        tsce = <optimized out>
        i = <optimized out>
        type = <optimized out>
        __FUNCTION__ = "skill_castend_nodamage_id"
#2  0x00000000006587b3 in skill_castend_id (tid=<optimized out>, tick=tick@entry=7856829541,
    id=<optimized out>, data=data@entry=0) at skill.cpp:11879
        fail = false
        res = <optimized out>
        target = <optimized out>
        src = 0x8ac09d0
        sd = <optimized out>
        md = <optimized out>
        ud = <optimized out>
        sc = <optimized out>
        flag = <optimized out>
#3  0x00000000006acf8f in unit_skilluse_id2 (src=0x8ac09d0, target_id=2004485,
    skill_id=<optimized out>, skill_lv=<optimized out>, casttime=0, castcancel=<optimized out>)
    at unit.cpp:2040
        ud = <optimized out>
---Type <return> to continue, or q <return> to quit---
        tstatus = 0x8ac0eb0
        sc = <optimized out>
        sd = 0x8ac09d0
        target = 0x8ac09d0
        tick = <optimized out>
        combo = 0
        range = <optimized out>
        __FUNCTION__ = "unit_skilluse_id2"
        inf = <optimized out>
        skill = <optimized out>
#4  0x000000000048174b in clif_parse (fd=17) at clif.cpp:22164
        cmd = <optimized out>
        packet_len = 10
        sd = 0x8ac09d0
        pnum = 0
        cmd2 = -457710592
#5  0x0000000000412475 in do_sockets (next=<optimized out>) at socket.cpp:1024
        rfd = {fds_bits = {131072, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 42437}
        ret = <optimized out>
        i = 17
#6  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:381
No locals.
(gdb)
```
