### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by sinju92** [rathena/rathena#7146]
* **rAthena Hash**: 

caa5cdd

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: Random Crash
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  
#0  0x000055555568289e in map_delblock (bl=bl@entry=0x55556955d980) at map.cpp:407
        pos = <optimized out>
        mapdata = <optimized out>
#1  0x000055555586c37e in unit_remove_map_ (bl=bl@entry=0x55556955d980,
    clrtype=clrtype@entry=CLR_RESPAWN, file=file@entry=0x555555927f1e "unit.cpp",
    line=line@entry=3319,
    func=func@entry=0x5555559281f0 <unit_remove_map_pc(map_session_data*, clr_type)::__FUNCTION__> "unit_remove_map_pc") at unit.cpp:3281
        ud = <optimized out>
        sc = 0x55556955df08
#2  0x000055555586d0eb in unit_remove_map_pc (sd=sd@entry=0x55556955d980,
    clrtype=clrtype@entry=CLR_RESPAWN) at unit.cpp:3319
        __FUNCTION__ = "unit_remove_map_pc"
#3  0x00005555556877a5 in map_quit (sd=0x55556955d980) at map.cpp:2133
        i = <optimized out>
        mapdata = <optimized out>
#4  0x00005555555ea538 in chrif_disconnectplayer (fd=fd@entry=8) at chrif.cpp:1206
        sd = <optimized out>
        account_id = <optimized out>
#5  0x00005555555ed0d7 in chrif_parse (fd=8) at chrif.cpp:1837
        cmd = 11039
        packet_len = 7
        fd = <optimized out>
        packet_len = <optimized out>
        cmd = <optimized out>
        r = <optimized out>
        packet_len = <optimized out>
        cmd = <optimized out>
        r = <optimized out>
#6  0x000055555587640d in do_sockets (next=<optimized out>) at socket.cpp:1421
        ret = <optimized out>
        i = 8
#7  0x0000555555583bce in main (argc=1, argv=0x7fffffffdfb8) at core.cpp:384
        next = <optimized out>
(gdb)
* **Modifications that may affect results**:  Gepard, AFK

**Comment by admkakaroto** [comment]
Using any bg mod?

**Comment by sinju92** [comment]
> Using any bg mod?

No just afk and gepard
