### ISSUE TITLE
Map-Crash in WoE

### ISSUE THREAD

**Issue by SiberianSS** [rathena/rathena#7148]
Last Revision rAthena
Pre-Renewal
Client: 2015-11-04
Using Euphy's WOE Controller
```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from revolution_map-server...

warning: core file may not match specified executable file.
[New LWP 12306]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./revolution_map-server'.
Program terminated with signal SIGBUS, Bus error.
#0  0x0000556828967581 in _mfree (ptr=0x556867e66ffc, file=file@entry=0x5568289e1718 "pc.cpp", line=line@entry=10900, func=func@entry=0x5568289e18ec "pc_setregstr") at malloc.cpp:391
391                     if(
(gdb) bt full
#0  0x0000556828967581 in _mfree (ptr=0x556867e66ffc, file=file@entry=0x5568289e1718 "pc.cpp", line=line@entry=10900, func=func@entry=0x5568289e18ec "pc_setregstr") at malloc.cpp:391
        head_large = 0x556867e66fcc
        head = 0x556867e66fe4
#1  0x00005568287d938c in pc_setregstr (sd=sd@entry=0x556869f77ad0, reg=reg@entry=16677, str=str@entry=0x7ffe25bcb29c "gefg_cas02") at pc.cpp:10900
        p = 0x7f8995aea5fc
        index = 0
        prev = {type = DB_DATA_PTR, u = {i = -1783716356, ui = 2511250940, ptr = 0x7f8995aea5fc, i64 = 140228898498044}}
        __FUNCTION__ = "pc_setregstr"
#2  0x0000556828885d6e in set_reg_str (st=st@entry=0x7f8995ba082c, sd=0x556869f77ad0, num=num@entry=16677, name=0x5568648d532f "@map$", value=value@entry=0x7ffe25bcb29c "gefg_cas02", ref=0x0) at script.cpp:3155
        prefix = <optimized out>
        vlen = <optimized out>
        __FUNCTION__ = "set_reg_str"
#3  0x000055682888b8db in buildin_getmapxy (st=0x7f8995ba082c) at script.cpp:15978
        bl = <optimized out>
        sd = 0x556869f77ad0
        num = 16677
        name = <optimized out>
        prefix = <optimized out>
        x = 76
        y = 42
        type = <optimized out>
        mapname = "gefg_cas02\000"
        __FUNCTION__ = "buildin_getmapxy"
#4  0x000055682885698b in run_func (st=st@entry=0x7f8995ba082c) at script.cpp:4133
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        end_sp = <optimized out>
        func = 820
#5  0x000055682885ca78 in run_script_main (st=0x7f8995ba082c) at script.cpp:4413
        c = <optimized out>
        cmdcount = <optimized out>
        gotocount = 2038
        sd = <optimized out>
        stack = 0x5568397f7144
#6  0x000055682879ef79 in npc_event_sub(map_session_data*, event_data*, char const*) () at /usr/include/c++/9/bits/stl_vector.h:347
No symbol table info available.
#7  0x00005568287ae6e5 in npc_script_event(map_session_data*, npce_event) () at /usr/include/c++/9/bits/stl_vector.h:347
No symbol table info available.
#8  0x00005568287024af in clif_parse_LoadEndAck (fd=<optimized out>, sd=0x556869f77ad0) at clif.cpp:11319
        guild_notice = false
        mapdata = 0x556828cfc640 <map+1778656>
#9  0x00005568286cd00a in clif_parse (fd=164) at clif.cpp:24346
        cmd = <optimized out>
        packet_len = 2
        sd = <optimized out>
        pnum = 0
#10 0x0000556828962365 in do_sockets (next=<optimized out>) at socket.cpp:1406
        rfd = {fds_bits = {0, 0, 68719476736, 0 <repeats 13 times>}}
        timeout = {tv_sec = 0, tv_usec = 19915}
        ret = <optimized out>
        i = 164
#11 0x000055682865e00d in main (argc=1, argv=0x7ffe25bcb888) at core.cpp:382
        next = <optimized out>
```

**Comment by aleos89** [comment]
Can you explain how the crash happened? Just giving the crash dump doesn't always explain the full situation.

**Comment by Akkarinage** [comment]
Euphy's WoE Controller works fine out of the box under normal circumstances - since the user has failed to provide any meaningful information, I'm closing this Issue.

Issue can be re-opened with additional information at a later date, if the user can provide it.
