### ISSUE TITLE
Mapcrash from map_foreachinrangeV 

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7199]
* **rAthena Hash**: 5d105b5
* **Client Date**: 2021-11-18
* **Server Mode**: Pre-renewal
* **Description of Issue**: 
* 
```
#0  map_foreachinrangeV (func=0x530600 <mob_ai_sub_hard_activesearch(block_list *, typedef __va_list_tag __va_list_tag *)>, center=0xec3b5ec, range=range@entry=10, type=27, ap=ap@entry=0x7ffc0fb13d68, wall_check=wall_check@entry=false)
    at map.cpp:703
703     map.cpp: No such file or directory.
Missing separate debuginfos, use: yum debuginfo-install MariaDB-shared-10.4.25-1.el8.x86_64 glibc-2.28-189.5.el8_6.x86_64 libgcc-8.5.0-10.el8.alma.x86_64 libstdc++-8.5.0-10.el8.alma.x86_64 openssl-libs-1.1.1k-6.el8_5.x86_64 pcre-8.42-6.el8.x86_64 zlib-1.2.11-18.el8_5.x86_64
(gdb) bt full
#0  map_foreachinrangeV (func=0x530600 <mob_ai_sub_hard_activesearch(block_list *, typedef __va_list_tag __va_list_tag *)>, center=0xec3b5ec, range=range@entry=10, type=27, ap=ap@entry=0x7ffc0fb13d68, wall_check=wall_check@entry=false)
    at map.cpp:703
        bx = 18
        by = <optimized out>
        m = 154
        returnCount = 0
        bl = 0xfdfdfdfdfdfdfdfd
        blockcount = <optimized out>
        i = <optimized out>
        x0 = 140
        x1 = 160
        y0 = 109
        y1 = 129
        ap_copy = {{gp_offset = 0, fp_offset = 2, overflow_arg_area = 0x7ffc0fb13e48, reg_save_area = 0x7ffc0fb13d80}}
        mapdata = 0xc53120 <map+1471008>
#1  0x00000000005197e3 in map_foreachinallrange (func=func@entry=0x530600 <mob_ai_sub_hard_activesearch(block_list *, typedef __va_list_tag __va_list_tag *)>, center=center@entry=0xec3b5ec, range=range@entry=10, type=<optimized out>)
    at map.cpp:766
        returnCount = 0
        ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffc0fb13e40, reg_save_area = 0x7ffc0fb13d80}}
#2  0x000000000053c9b7 in mob_ai_sub_hard (md=md@entry=0xec3b5ec, tick=tick@entry=836760021) at mob.cpp:1813
        tbl = 0x0
        abl = <optimized out>
        mode = 14469
        view_range = 10
        can_move = 0
        slave_lost_target = false
#3  0x000000000053d42b in mob_ai_sub_hard_timer(block_list *, typedef __va_list_tag __va_list_tag *) (bl=0xec3b5ec, ap=<optimized out>) at mob.cpp:1970
        md = 0xec3b5ec
        char_id = 161347
        tick = 836760021
#4  0x000000000051958c in map_foreachinrangeV (func=0x53d3f0 <mob_ai_sub_hard_timer(block_list *, typedef __va_list_tag __va_list_tag *)>, center=0x13ac8080, range=<optimized out>, type=<optimized out>, ap=ap@entry=0x7ffc0fb13f98,
    wall_check=wall_check@entry=false) at map.cpp:740
        bx = <optimized out>
        by = <optimized out>
        m = 154
        returnCount = 0
        bl = <optimized out>
        blockcount = <optimized out>
        i = 0
        x0 = <optimized out>
        x1 = <optimized out>
        y0 = <optimized out>
        y1 = <optimized out>
        ap_copy = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffc0fb14070, reg_save_area = 0x7ffc0fb13fb0}}
        mapdata = 0xc53120 <map+1471008>
#5  0x00000000005197e3 in map_foreachinallrange (func=func@entry=0x53d3f0 <mob_ai_sub_hard_timer(block_list *, typedef __va_list_tag __va_list_tag *)>, center=<optimized out>, range=<optimized out>, type=type@entry=2) at map.cpp:766
        returnCount = 0
        ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffc0fb14070, reg_save_area = 0x7ffc0fb13fb0}}
#6  0x000000000052f271 in mob_ai_sub_foreachclient(map_session_data *, typedef __va_list_tag __va_list_tag *) (sd=<optimized out>, ap=<optimized out>) at mob.cpp:1984
        tick = <optimized out>
#7  0x000000000051cd3a in map_foreachpc (func=func@entry=0x52f230 <mob_ai_sub_foreachclient(map_session_data *, typedef __va_list_tag __va_list_tag *)>) at map.cpp:2398
        args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ffc0fb14170, reg_save_area = 0x7ffc0fb140a0}}
        ret = <optimized out>
        iter = 0x7fbbee15921c
        sd = 0x13ac8080
#8  0x000000000052fe1c in mob_ai_hard (tid=<optimized out>, tick=<optimized out>, id=<optimized out>, data=<optimized out>) at mob.cpp:2091
No locals.
#9  0x0000000000709c26 in do_timer (tick=<optimized out>) at timer.cpp:372
        tid = 11
        diff = -1
        __FUNCTION__ = "do_timer"
#10 0x000000000041c408 in main (argc=1, argv=0x7ffc0fb142e8) at core.cpp:381
--Type <RET> for more, q to quit, c to continue without paging--
        next = <optimized out>
```

**Comment by hnomkeng** [comment]
```
#0  map_foreachinareaV (func=
    0x487030 <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)                                                                                                                                                             >, m=192, x0=195, y0=169, x1=223, y1=197, type=1, ap=0x7ffdad9f4358,
    wall_check=false) at map.cpp:832
832     map.cpp: No such file or directory.
Missing separate debuginfos, use: yum debuginfo-install MariaDB-shared-10.4.25-1                                                                                                                                                             .el8.x86_64 glibc-2.28-189.5.el8_6.x86_64 libgcc-8.5.0-10.el8.alma.x86_64 libstd                                                                                                                                                             c++-8.5.0-10.el8.alma.x86_64 openssl-libs-1.1.1k-6.el8_5.x86_64 pcre-8.42-6.el8.                                                                                                                                                             x86_64 zlib-1.2.11-18.el8_5.x86_64
(gdb) ิbtfull
Undefined command: "btfull".  Try "help".
(gdb) bt full
#0  map_foreachinareaV (func=0x487030 <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)>, m=192, x0=195, y0=169, x1=223, y1=197, type=1, ap=0x7ffdad9f4358,
    wall_check=false) at map.cpp:832
        bx = 27
        by = <optimized out>
        cx = 0
        cy = 0
        returnCount = 0
        bl = 0xfdfdfdfdfdfdfdfd
        blockcount = <optimized out>
        i = <optimized out>
        ap_copy = {{gp_offset = 0, fp_offset = 0, overflow_arg_area = 0x0, reg_save_area = 0x0}}
        mapdata = 0xcb1680 <map+1833984>
#1  0x000000000051c3a3 in map_foreachinallarea (func=func@entry=0x487030 <clif_send_sub(block_list *, typedef __va_list_tag __va_list_tag *)>, m=<optimized out>,
    x0=<optimized out>, y0=<optimized out>, x1=<optimized out>, y1=<optimized out>, type=1) at map.cpp:879
        returnCount = 0
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffdad9f4438, reg_save_area = 0x7ffdad9f4370}}
#2  0x00000000004a8017 in clif_send (buf=0x7ffdad9f44f0, len=16, bl=0xbc634ec, type=AREA_WOS) at clif.cpp:934
        i = <optimized out>
        sd = <optimized out>
        tsd = <optimized out>
        p = 0x0
        g = 0x0
        bg = std::shared_ptr<s_battleground_data> (empty) = {get() = 0x0}
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = <optimized out>
        iter = <optimized out>
        __FUNCTION__ = "clif_send"
#3  0x00000000004b3efb in clif_move (ud=ud@entry=0xbc6350c) at clif.cpp:2469
        buf = "\206\000s\221\220\006\064Ks@\263\210\201LBC"
        vd = 0x54d774c
        bl = 0xbc634ec
        sc = <optimized out>
#4  0x0000000000700c67 in unit_walktoxy_sub (bl=0xbc634ec) at unit.cpp:134
        ud = 0xbc6350c
        wpd = {path_len = 4 '\004', path_pos = 0 '\000', path = {DIR_SOUTHWEST, DIR_SOUTH, DIR_SOUTH, DIR_SOUTH, DIR_NORTH <repeats 28 times>}}
        i = <optimized out>
        __FUNCTION__ = "unit_walktoxy_sub"
        ud = <optimized out>
        wpd = <optimized out>
        i = <optimized out>
        dir = <optimized out>
#5  unit_walktoxy_sub (bl=0xbc634ec) at unit.cpp:79
        ud = <optimized out>
        wpd = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "unit_walktoxy_sub"
        dir = <optimized out>
#6  0x000000000070114f in unit_walktoxy (bl=bl@entry=0xbc634ec, x=<optimized out>, x@entry=208, y=<optimized out>, y@entry=179, flag=flag@entry=0 '\000') at unit.cpp:787
--Type <RET> for more, q to quit, c to continue without paging--
        __FUNCTION__ = "unit_walktoxy"
        ud = 0xbc6350c
        wpd = {path_len = 4 '\004', path_pos = 0 '\000', path = {DIR_SOUTHWEST, DIR_SOUTH, DIR_SOUTH, DIR_SOUTH, DIR_NORTH <repeats 28 times>}}
        sc = <optimized out>
        sd = <optimized out>
#7  0x000000000053e418 in mob_randomwalk (tick=1128418420, md=0xbc634ec) at mob.cpp:1604
        x = <optimized out>
        y = <optimized out>
        i = 0
        c = <optimized out>
        dx = -1
        speed = <optimized out>
        d = <optimized out>
        r = <optimized out>
        rdir = 0
        dy = -4
        d = <optimized out>
        i = <optimized out>
        c = <optimized out>
        r = <optimized out>
        rdir = <optimized out>
        dx = <optimized out>
        dy = <optimized out>
        max = <optimized out>
        speed = <optimized out>
        __FUNCTION__ = "mob_randomwalk"
        x = <optimized out>
        y = <optimized out>
#8  mob_randomwalk (md=0xbc634ec, tick=1128418420) at mob.cpp:1571
        i = <optimized out>
        c = <optimized out>
        r = <optimized out>
        rdir = <optimized out>
        dx = <optimized out>
        dy = <optimized out>
        max = <optimized out>
        speed = <optimized out>
        __FUNCTION__ = "mob_randomwalk"
        x = <optimized out>
        y = <optimized out>
#9  0x000000000053fbb0 in mob_ai_sub_lazy (args=<optimized out>, md=0xbc634ec) at mob.cpp:2085
        tick = 1128418420
        __FUNCTION__ = "mob_ai_sub_lazy"
        tick = <optimized out>
#10 mob_ai_sub_lazy(mob_data *, typedef __va_list_tag __va_list_tag *) (md=0xbc634ec, args=<optimized out>) at mob.cpp:2017
        tick = <optimized out>
        __FUNCTION__ = "mob_ai_sub_lazy"
#11 0x000000000051f38a in map_foreachmob (func=func@entry=0x53f950 <mob_ai_sub_lazy(mob_data *, typedef __va_list_tag __va_list_tag *)>) at map.cpp:2421
        args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ffdad9f4750, reg_save_area = 0x7ffdad9f4680}}
        ret = <optimized out>
        iter = 0x7f24dbde51f4
        md = 0xbc634ec
#12 0x0000000000531fe0 in mob_ai_lazy (tid=<optimized out>, tick=<optimized out>, id=<optimized out>, data=<optimized out>) at mob.cpp:2104
No locals.
#13 0x000000000070ded6 in do_timer (tick=<optimized out>) at timer.cpp:372
        tid = 12
        diff = -1
        __FUNCTION__ = "do_timer"
#14 0x000000000041c4f8 in main (argc=1, argv=0x7ffdad9f48c8) at core.cpp:381
        next = <optimized out>
```

**Comment by Lemongrass3110** [comment]
As discussed in discord this is most likely due to your custom modifcations to the mob chasing code.
