### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7292]
### rAthena Hash

ba9770c

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

```
Program received signal SIGSEGV, Segmentation fault.
pet_endautobonus (tid=169201, tick=<optimized out>, id=<optimized out>, data=<optimized out>)
    at pet.cpp:2445
2445            for (std::shared_ptr<s_petautobonus> autobonus : *bonus) {
Missing separate debuginfos, use: debuginfo-install MariaDB-shared-10.2.43-1.el7.centos.x86_64 glibc-2.17-325.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb)

(gdb) bt full
#0  pet_endautobonus (tid=169201, tick=<optimized out>, id=<optimized out>, data=<optimized out>)
    at pet.cpp:2445
        __for_range = <optimized out>
        sd = 0x5209ac0
        bonus = <optimized out>
        __FUNCTION__ = "pet_endautobonus"
#1  0x0000000000722be0 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 169201
        diff = -5
        __FUNCTION__ = "do_timer"
#2  0x000000000040f213 in main (argc=1, argv=0x7fffffffde98) at core.cpp:381
        next = <optimized out>
(gdb)
```

### Expected Result

server work normaly

### How to Reproduce

i dont know

### Official Information

not have information on aegis like what

**Comment by sonniez** [comment]
confirmed this issue.

**Comment by Anjuts** [comment]
confirmed
