### ISSUE TITLE
Convex Mirror Map Crash

### ISSUE THREAD

**Issue by Gyakushinn** [rathena/rathena#8083]
### rAthena Hash

9c06340f3a3cbe5f8c2bb92fe11ecb8950a43e8c

### Client Date

2021-11-17

### Server Mode

Pre-Renewal

### Result

1. Use Convex Mirror in Map MvP
2. Show Location MvP in Mini Map
3. Kill MvP
4. Display Description Time Map Re-Spawn in Chat
5. Re-Login Character and Login Again
5.1 Map Crash
6. I'll delete sc_data in mysql type 259
6.1 I'll login character again
6.2 normally

if use convex mirror again will encounter problems again

### Relevant Log Output

```Shell
#0  0x000000000049889d in clif_bossmapinfo (sd=sd@entry=0x761ac60, md=0x0,
    flag=flag@entry=BOSS_INFO_ALIVE_WITHMSG) at clif.cpp:17634
        fd = 9
        __FUNCTION__ = "clif_bossmapinfo"
#1  0x00000000007318a5 in status_change_start (src=src@entry=0x0,
    bl=bl@entry=0x761ac60, type=<optimized out>, rate=rate@entry=10000,
    val1=<optimized out>, val2=<optimized out>, val3=<optimized out>,
    val4=<optimized out>, duration=<optimized out>, flag=<optimized out>,
    delay=<optimized out>) at status.cpp:13002
        calc_flag = <optimized out>
        opt_flag = <optimized out>
        disable_opt_flag = 0
        sd = <optimized out>
        sce = 0x673585c
        status = <optimized out>
        vd = <optimized out>
        undead_flag = <optimized out>
        tick_time = <optimized out>
        sc_isnew = true
        scdb = std::shared_ptr (count 3, weak 0) 0x0
        __FUNCTION__ = "status_change_start"
        tick = 777
        endlist = std::vector of length 0, capacity 0
---Type <return> to continue, or q <return> to quit---
```

### Expected Result

NA

### How to Reproduce

NA

### Official Information

NA

**Comment by Lemongrass3110** [comment]
Most likely related to #2509
