### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8359]
### rAthena Hash

aa62b2f

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

```
Program received signal SIGSEGV, Segmentation fault.
clif_wis_message (sd=sd@entry=0x4cf6620, nick=<optimized out>,
    mes=mes@entry=0x7fffffffd100 "Cherry is in autotrade mode and cannot receive whispered messages.", mes_len=66, gmlvl=gmlvl@entry=0) at clif.cpp:7094
7094            p->senderGID = ssd->bl.id;
(gdb)
```

```
(gdb) bt full
#0  clif_wis_message (sd=sd@entry=0x4cf6620, nick=<optimized out>,
    mes=mes@entry=0x7fffffffd100 "Cherry is in autotrade mode and cannot receive whispered messages.", mes_len=66, gmlvl=gmlvl@entry=0) at clif.cpp:7094
        ssd = 0x0
#1  0x00000000004b64fa in clif_parse_WisMessage (fd=14, sd=0x4cf6620) at clif.cpp:12032
        dstsd = 0x12a186b0
        i = <optimized out>
        target = "Cherry", '\000' <repeats 18 times>
        message = "hello sis", '\000' <repeats 244 times>
        output = "Cherry is in autotrade mode and cannot receive whispered messages.", '\000' <repeats 238 times>
        __FUNCTION__ = "clif_parse_WisMessage"
#2  0x0000000000490f5b in clif_parse (fd=14) at clif.cpp:25451
        cmd = <optimized out>
        packet_len = 39
        sd = 0x4cf6620
        pnum = 0
        cmd2 = -7910
#3  0x0000000000765bb5 in do_sockets (next=<optimized out>) at socket.cpp:1026
        rfd = {fds_bits = {16384, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 235}
        ret = <optimized out>
        i = 14
#4  0x00000000007634a8 in handle_main (next=<optimized out>, this=0x7fffffffdd90) at core.cpp:432
No locals.
#5  rathena::server_core::Core::start (this=this@entry=0x7fffffffdd90, argc=1, argv=0x7fffffffde98)
    at core.cpp:391
        next = <optimized out>
#6  0x000000000040c9fa in main_core<rathena::server_map::MapServer> (argv=<optimized out>,
    argc=<optimized out>) at ../common/core.hpp:102
        server = {<rathena::server_core::Core> = {
            _vptr.Core = 0x7eb090 <vtable for rathena::server_map::MapServer+16>,
            m_status = rathena::server_core::RUNNING, m_type = rathena::server_core::MAP,
            m_run_once = false, m_crashed = false}, <No data fields>}
---Type <return> to continue, or q <return> to quit---
#7  main (argc=<optimized out>, argv=<optimized out>) at map.cpp:5308
No locals.
(gdb)
```

### Expected Result

Server Run Normal

### How to Reproduce

Sorry I don't know what's going on, I can only attach GDB bt full

From GDB bt full it looks like it's related to clif_parse_WisMessage

### Official Information

N/A

**Comment by dzurrahman** [comment]
![image](https://github.com/rathena/rathena/assets/56845420/a0cde67d-ef4f-40d1-90a8-95b8b4d8296f)

you can turn off that line of code first, then compile it, This is only temporary.
