### ISSUE TITLE
[Char Server] - Received a crash signal (Program received signal SIGSEGV)

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8432]
### rAthena Hash

https://github.com/rathena/rathena/commit/8c4d1bb0c60b0278e63d6134b342cb3349aeabaa

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

[Fatal Error]: Received a crash signal, trying to handle it as good as possible! Segmentation fault

```
Program received signal SIGSEGV, Segmentation fault.
chclif_parse (fd=<optimized out>) at char_clif.cpp:1598
1598                                            if( sd->pincode_correct ){
Missing separate debuginfos, use: debuginfo-install MariaDB-shared-10.4.34-1.el7.centos.x86_64 glibc-2.17-326.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-54.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb)
```

```
(gdb) bt full
#0  chclif_parse (fd=<optimized out>) at char_clif.cpp:1598
        next = 1
        cmd = 3
        sd = 0x0
        ipl = 769916465
#1  0x0000000000445a55 in do_sockets (next=<optimized out>) at socket.cpp:1026
        rfd = {fds_bits = {8192, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 692997}
        ret = <optimized out>
        i = 13
#2  0x0000000000443348 in handle_main (next=<optimized out>, this=0x7fffffffdf90) at core.cpp:432
No locals.
#3  rathena::server_core::Core::start (this=this@entry=0x7fffffffdf90, argc=1, argv=0x7fffffffe098)
    at core.cpp:391
        next = <optimized out>
#4  0x00000000004047da in main_core<rathena::server_character::CharacterServer> (
    argv=<optimized out>, argc=<optimized out>) at ../common/core.hpp:102
        server = {<rathena::server_core::Core> = {
            _vptr.Core = 0x4a1d60 <vtable for rathena::server_character::CharacterServer+16>,
            m_status = rathena::server_core::RUNNING, m_type = rathena::server_core::CHARACTER,
            m_run_once = false, m_crashed = false}, <No data fields>}
#5  main (argc=<optimized out>, argv=<optimized out>) at char.cpp:3282
No locals.
(gdb)
```

### Expected Result

Char server works as it should and does not crash.

### How to Reproduce

N/A

### Official Information

N/A

### Modifications that may affect results

Maybe related: 
https://github.com/rathena/rathena/commit/6fdaac4a75fc6a7adbe697e248c8eebcb4d72dd1
https://github.com/rathena/rathena/commit/8c4d1bb0c60b0278e63d6134b342cb3349aeabaa

**Comment by gmragnarok** [comment]
Update, I have provided the information GDB bt full
